### ISSUE TITLE
Bug in max_dist early stopping

### ISSUE THREAD

**Issue by probberechts** [wannesm/dtaidistance#101]
The Python version of `dtw.distance` gives incorrect results when a `max_dist` upper bound is used. The C version gives the correct result.

**Example:**
```Python
dist1 = distance(np.loadtxt('s1.txt'), np.loadtxt('s2.txt'), max_dist=.20)  # result: inf
dist2 = distance(np.loadtxt('s1.txt'), np.loadtxt('s2.txt'))                # result: 0.19
assert dist1 == dist2
```
[s1.txt](https://github.com/wannesm/dtaidistance/files/5655445/s1.txt)
[s2.txt](https://github.com/wannesm/dtaidistance/files/5655447/s2.txt)

Removing [line 178](https://github.com/wannesm/dtaidistance/blob/2ec754d37bdd7c2bea1fb074257bcb1ac38ba59b/dtaidistance/dtw.py#L178) fixes this, but I am not sure whether that line is there for a specific reason.

**Comment by wannesm** [comment]
It was a bug in the distance function. This is fixed in 0e29e05bce2ca7f7e0870076ae6971b23c93bd05
