### ISSUE TITLE
compute normalized similarity measure from 2d dtw 

### ISSUE THREAD

**Issue by mok33** [wannesm/dtaidistance#104]
I have two 2d time series (one serie : list of x, y coordinates). I want to compute a normalized similarity measure from dtw distance between two series. As presented here : https://cs.stackexchange.com/questions/53250/normalized-measure-from-dynamic-time-warping

In my case the sample range is [0,28], so I was expecting M = 28 * template serie length to be a good upper bound. But that depends on what cost function is used ? is it a Manhattan or euclidean cost ?  I hope my question makes senses. I am doing this to see if a trajectory match another one.

**Comment by wannesm** [comment]
Euclidean distance is an upper bound for DTW (it's the diagonal in the cumulative cost matrix).
https://dtaidistance.readthedocs.io/en/latest/modules/dtw.html#dtaidistance.dtw.ub_euclidean
