### ISSUE TITLE
compare distance of one vector to list of vectors without loop

### ISSUE THREAD

**Issue by codool** [wannesm/dtaidistance#105]
Hello,
I am wondering if there is a better way to compute the dtw distance between one vector and a set of vectors without using a for loop, which increases runtime:

given:
vectorOne = [1,2,3,4,5]
vectorList = [[1,5,3,5,1], [5,6,3,2,1,],[1,4,4,4,5,]]

wanted:
distanceList=[0.1, 4.3, 3.2]

Thank you!

**Comment by wannesm** [comment]
You mean how to push the for loop to the C code, I assume. There's always a for loop somewhere. The C code assumes that all sequences are part of one data structure. You can indicate which subset you want to compute:

```
>>> vectorList = [[1,2,3,4,5], [1,5,3,5,1], [5,6,3,2,1,],[1,4,4,4,5,]]
>>> dtw.distance_matrix(vectorList, block=((0,1), (1,4)), compact=True, use_c=True)
array('d', [4.69041575982343, 7.211102550927978, 1.4142135623730951])
```

Which is conceptually the same as:

```
>>> [dtw.distance([1,2,3,4,5], y) for y in [[1,5,3,5,1], [5,6,3,2,1,],[1,4,4,4,5,]]]
[4.69041575982343, 7.211102550927978, 1.4142135623730951]
```

**Comment by codool** [comment]
Best thanks the library is very useful!
