### ISSUE TITLE
Documentation does not display the clustering module

### ISSUE THREAD

**Issue by macrocosme** [wannesm/dtaidistance#106]
Hi,  

  First of all, I really like your software package. 

It would be nice to have access to the functions documentation of the clustering module. I see it is included in index.rst but does not show up on readthedocs.

**Comment by wannesm** [comment]
Thanks for the notification. The clustering documentation is now generated and available at https://dtaidistance.readthedocs.io/en/latest/modules/clustering.html . The clustering is quite new so documenting everything is work in progress.

**Comment by macrocosme** [comment]
Super, thanks!
