### ISSUE TITLE
dtw.distance_matrix vs. dtw.distance_matrix_fast

### ISSUE THREAD

**Issue by smorvan** [wannesm/dtaidistance#108]
Thx for this fantastic piece of hardware.

I am using it to compute the distance between multiple time series. In my case (OS X / Catalina 10.15.7, Anaconda 4.9.2, Python 

When using dtw.distance_matrix vs. dtw.distance_matrix_fast I get completely different results. I suspect the dtw.distance_matrix_fast is having problems because the matrix is full of 0s, whereas it slower sibling returns something more meaningful.

I am enclosing a screen cap of the example.
<img width="854" alt="Screenshot 2021-01-18 at 20 50 45" src="https://user-images.githubusercontent.com/16397577/104957698-eda3c480-59ce-11eb-8051-3acffb03389c.png">

**Comment by wannesm** [comment]
Thanks for the report. This is the same problem as issue #96. I have not yet been able to reproduce this issue.

If possible, the log resulting from the following command could be informative (it forces the compilation):

```
pip install -vvv --upgrade --force-reinstall --no-deps --no-binary :all: dtaidistance
```

**Comment by wannesm** [comment]
I have identified a possible cause, see: https://github.com/wannesm/dtaidistance/issues/96#issuecomment-762813890
