### ISSUE TITLE
clustering plots: Issues if the series contain sequences of differing length 

### ISSUE THREAD

**Issue by hejung** [wannesm/dtaidistance#110]
Current behavior:
Fit a clustering model with a set of timeseries with differing lengths. When using the `model.plot` function for the hierarchical and metoid cluster models all plotted timeseries are truncated at the length of the first timeseries in the list.

Expected behavior:
(I) Either truncate at the maximum of the lengths of all timeseries [or (II) scale each timeseries separately such that it completely fits?]

For the hierarchical clustering changing [this](https://github.com/wannesm/dtaidistance/blob/28542d9300125615c541708428a03e17a00b854a/dtaidistance/clustering/hierarchical.py#L308) line to
```python
ax[1].set_xlim(left=0, right=ts_left_margin + ts_sample_length * max(len(s) for s in self.series))
```
has the effect of enabeling expected behavior (I).
Let me know if I should prepare a PR for (I), for (II) I would probably need to dive a bit deeper into the plot function.

Edit: Example plots for current and expected (I) behavior, both for the same set of timeseries.
Current:
![current](https://user-images.githubusercontent.com/19654054/107234699-37a72580-6a24-11eb-931e-579ce1e4d25d.png)

Expected (I)/ truncated at maxlength of longest timeseries:
![truncated](https://user-images.githubusercontent.com/19654054/107234807-573e4e00-6a24-11eb-8183-32c720e5f23e.png)

**Comment by wannesm** [comment]
Thanks for the good suggestion and visual example. I have integrated into the master branch.

**Comment by hejung** [comment]
Thank you for the fast reply and the usefull software!

The issue is still present in the Medoids class on both axis (these two lines):
https://github.com/wannesm/dtaidistance/blob/a551d61c6c8f628b2b87439ae3e0d0e0b8568d65/dtaidistance/clustering/medoids.py#L69
https://github.com/wannesm/dtaidistance/blob/a551d61c6c8f628b2b87439ae3e0d0e0b8568d65/dtaidistance/clustering/medoids.py#L72

**Comment by wannesm** [comment]
Good point. I've updated it in master.

**Comment by hejung** [comment]
Thanks again for the fast responses!
