### ISSUE TITLE
warping_paths_fast problem with many points

### ISSUE THREAD

**Issue by eikmeier-cn** [wannesm/dtaidistance#111]
Hi.

First of all I would like to congratulate you for the excellent tool. I am a Ph.D. student in the field of applied seismology and I use dtaidistance. In version 2.1.2 I used `warping_paths_fast` (without openMP) with series with 1500 points and there was no problem. In version 2.2.0 the tool no longer supports so many points (in the current version either). With 1000 it works, but with 1500 it doesn't, running exactly the same code. It presents the error that I am sharing below. Is that a bug?

Thanks!

![erro](https://user-images.githubusercontent.com/53953620/107721490-89b5a880-6cbb-11eb-9493-2f76eec6fed0.jpg)

**Comment by wannesm** [comment]
Thanks for the detailled explanation. This was indeed a bug that was introduced when removing the strict numpy dependencies. The method requested memory for 1500**3 values instead of 1500**2. It is fixed in master and 2.2.5.

**Comment by eikmeier-cn** [comment]
I tested it on version 2.2.5 and it worked fine.
Thanks, @wannesm.
