### ISSUE TITLE
Matrix with all warping paths

### ISSUE THREAD

**Issue by eikmeier-cn** [wannesm/dtaidistance#113]
Hi all.

I have a question about the meaning of the color scale of the matrix below. In the documentation it says that the scale refers to "the matrix with all warping paths". However, wouldn't that be the cost matrix or the accumulated cost matrix? If not, please, what exactly means "the matrix with all warping paths".

![Ima](https://user-images.githubusercontent.com/53953620/108385842-d1bc5a00-71ea-11eb-8cbc-46704d8ff802.jpg)

Thanks.

**Comment by wannesm** [comment]
It is the accumulated cost matrix, yes. I've updated the documentation to also use this terminology.

If you want more details about the color scale, you can give `shownumbers=True` and/or `showlegend=True` to the `plot_warpingpaths` method.

**Comment by eikmeier-cn** [comment]
Thanks, @wannesm.
