### ISSUE TITLE
'Figure' object has no attribute 'add_artist'

### ISSUE THREAD

**Issue by YanJun211** [wannesm/dtaidistance#116]
AttributeError                            Traceback (most recent call last)
<ipython-input-16-86bb5da615be> in <module>()
      1 path = dtw.warping_path(s1, s2)
----> 2 dtwvis.plot_warping(s1, s2, path, filename="D:\warp.png")

~\Anaconda3\lib\site-packages\dtaidistance\dtw_visualisation.py in plot_warping(s1, s2, path, filename)
    121         lines.append(con)
    122     for line in lines:
--> 123         fig.add_artist(line)
    124     if filename:
    125         plt.savefig(filename)

AttributeError: 'Figure' object has no attribute 'add_artist'

**Comment by wannesm** [comment]
The add_artist method was added in version 3.0.0 (https://matplotlib.org/3.5.1/api/figure_api.html#matplotlib.figure.Figure.add_artist). Maybe an outdated matplotlib installation?
