### ISSUE TITLE
Support for ndim variants of warping_path and dba

### ISSUE THREAD

**Issue by ThenTech** [wannesm/dtaidistance#117]
In my project, I am working with high dimensional time series and want to calculate an average given a list of nD series.

Currently there are no `dtw_ndim_barycenter.dba` or `dtw_barycenter.dba_ndim` functions available. Moreover the 1D variant of `dba` uses `dtw_cc.warping_path` which returns the path itself, while the `dtw_ndim.warping_paths` returns a distance and a matrix and also has no C implementation.

Could a `dtw_ndim_barycenter.dba` (with C variant) be created?

**Comment by wannesm** [comment]
The implementation should be similar to the 1-dim variant (Python and C). It is, however, not on our short-term list since it is not required in our current research projects and we have not enough resources  to work on this (people or free time).

**Comment by wannesm** [comment]
n-dimensional support for warping_path, DBA and kmeans has been added to the master branch. We need some more testing and if all works fine it will appear in the next release.

**Comment by ThenTech** [comment]
That is good news. I will try to find some time to test this.
