### ISSUE TITLE
Can not import the dtaidistance 

### ISSUE THREAD

**Issue by kengan** [wannesm/dtaidistance#119]
I use the version 2.2.5 with python3.7 on window 10 with the following import

from dtaidistance import dtw
from dtaidistance import dtaidistancec_dtw

But I get error:
 cannot import name 'dtw' from 'dtaidistance'

Can you help me ? Thank you !

**Comment by ColinChrist** [comment]
`from dtaidistance import dtw` works on my machine. Are you sure, that you have installed the package correctly? 
`pip install dtaidistance`

**Comment by cloudy-sfu** [comment]
#125 Are you @kengan using Anaconda, and you @ColinChrist aren't?

**Comment by Goudabroetchen** [comment]
Can't import dtaidistance neither.
Using pycharm.

from dtaidistance import dtw
leads to the following error message:

  File "dtaidistance\util_numpy_cc.pyx", line 1, in init dtaidistance.dtw_cc_numpy
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

**Comment by jensheli** [comment]
any updates here on how to solve this?

**Comment by wannesm** [comment]
The issues mentioned in this thread are not detailed enough to replicate. The setup with Windows and OMP and/or Conda is hard to get working reliably on all variations of the platform so all feedback and help is welcome.

Also check the instructions on troubleshooting on https://dtaidistance.readthedocs.io/en/latest/usage/installation.html#from-pypi to see more hints about what the problem could be.

**Comment by wannesm** [comment]
There is now also a precompiled version available: https://anaconda.org/conda-forge/dtaidistance
