### ISSUE TITLE
Link error with pip install from PyPI

### ISSUE THREAD

**Issue by brownpanther** [wannesm/dtaidistance#12]
`    Generating code                                                                                                                                          Finished generating code                                                                                                                                 LINK : fatal error LNK1158: cannot run 'rc.exe'                                                                                                          error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1158 `

Cannot install this package due to this error when building the wheel. Do you know how to fix it?

**Comment by wannesm** [comment]
We have limited experience with running this package on a Windows system but this appears to be a problem with the Visual Studio installation. Not with this package. See also https://github.com/conan-io/conan/issues/1340#issuecomment-327950375

**Comment by brownpanther** [comment]
when I tried to install this package on Google Colab (ubuntu), I got an error similar to issue [#10](https://github.com/wannesm/dtaidistance/issues/10)
I assumed they were related. Is that not the case?
