### ISSUE TITLE
kNN subsequence search support?

### ISSUE THREAD

**Issue by fauxneticien** [wannesm/dtaidistance#120]
Hi — I was wondering whether it would be reasonably easy to approximate/replicate with dtaidistance the kNN subsequence search (with lower bounding and early abandoning) on multi-dimensional data that's available in the IncDTW R package. If so, any hints/tips would be greatly appreciated!

The [documentation](https://cran.r-project.org/web/packages/IncDTW/vignettes/Theory_and_Applications_for_the_R_Package_IncDTW.pdf) accompanying IncDTW from 2018 (page 4) said that dtaidistance doesn't support multi-variate series comparisons, which is not the case anymore with [`dtaidistance.dtw_ndim`](https://dtaidistance.readthedocs.io/en/latest/modules/dtw_ndim.html), but I was wondering about the kNN aspect.

I'm mostly working in python and am looking to simplify my data workflow (instead of passing data back and forth between R and python), and, if possible at all, am looking for a straightforward way to approximate IncDTW's kNN subsequence matching function in python. Thanks!

![Screen Shot 2021-04-03 at 1 31 24 AM](https://user-images.githubusercontent.com/9938298/113473203-e6605480-941c-11eb-9510-d663e3d09aea.png)
![Screen Shot 2021-04-03 at 1 34 14 AM](https://user-images.githubusercontent.com/9938298/113473201-e52f2780-941c-11eb-9370-799f25d36c51.png)

**Comment by wannesm** [comment]
I think the algorithm in the documentation can be implemented similarly. The `dtw.distance` method has a `max_dist` argument for early abandoning. You can pass the previously best distance. Or pass the Euclidean upper bound (`ub_euclidean`) as a first estimate. Maybe you can also be smart about parallellisation using the `block` argument.

The statement in the IncDTW documentation is indeed correct. Support for multivariate DTW was limited in 2018 (and the limited support that was available was not in the documentation).

**Comment by wannesm** [comment]
You might be interested that a subsequence search was added to the development branch. It's a different algorithm than incDTW or kNN. Instead it's based on psi-relaxation. This allows us to search for any length of possible match, instead of a given length. You can use it as follows (if you install from the development branch, https://github.com/wannesm/dtaidistance/tree/develop):

```
from dtaidistance.subsequence.dtw import subsequence_search
query = np.array([1., 2, 0])
series = np.array([1., 0, 1, 2, 1, 0, 2, 0, 3, 0, 0])
sa = subsequence_search(query, series)
mf = sa.matching_function()  # scores of all possible matches
best_match_end_idx = np.argmin(mf)  # best match
best_match_start_idx = sa.matching_function_startpoint(best_match_end_idx)
best_match_path = sa.matching_function_bestpath(best_match_end_idx)  # alignment path for best match
```
