### ISSUE TITLE
input dim for dtw

### ISSUE THREAD

**Issue by xiezhiqing0112** [wannesm/dtaidistance#129]
Does **dtw.distance_fast()** only support simgle dim to input? I use the (N, 3) for input, but got error File **"dtaidistance/dtw_cc.pyx", line 257, in dtaidistance.dtw_cc.distance
ValueError: Buffer has wrong number of dimensions (expected 1, got 2)**

**Comment by wannesm** [comment]
You need to use the dtw_ndim submodule: `dtw_ndim.distance_fast()`. The usage should be identical.

**Comment by xiezhiqing0112** [comment]
Thank you very much
