### ISSUE TITLE
Need support for subsequence dtaidistance

### ISSUE THREAD

**Issue by dayanand4u** [wannesm/dtaidistance#132]
Hi, I am using python 3.7.8 and I have installed dtaidistance using pip. When I executed sample code for subsequence, I am facing issue as "c the compiled dtaidistance c library is not available".

Could you please guide me how to resolve it. 
May I know the clear installation details. I am unable to find it documentation.

**Comment by dayanand4u** [comment]
Hi, Can you please help me out how to install and use dtaidistance subsequence alignment.

**Comment by wannesm** [comment]
The subsequence search is now available on pipy.

If the compilation fails, use verbose installation and check what error you get.  For more details, see the troubleshooting section in the documentation https://dtaidistance.readthedocs.io/en/latest/usage/installation.html#from-pypi .

**Comment by Friedino** [comment]
Thanks for the hint. 
I had the same issue as @dayanand4u  could resolve it with:
`pip install -vvv --upgrade --force-reinstall --no-deps --no-binary :all: dtaidistance`

**Comment by dayanand4u** [comment]
Hi @wannesm Thanks for input. I have facing still issue . **please help me to resolve it.**
I am using Windows 10 Environment ad Python Version as 3.7.8.
I am suspecting compiled C libraries are not available or not installing properly  in my PC.

I have installed dtaidistance with pip and now i am able to subsequence module under "C:\Python37\Lib\site-packages\dtaidistance" folder.

Now i have tried to execute the sample below script ;

from dtaidistance.subsequence.dtw import subsequence_alignment
from dtaidistance import dtw_visualisation as dtwvis
import numpy as np
import pandas as pd
s1 = np.array([[0, 0],
               [0, 1],
               [2, 1],
               [0, 1],
               [0, 0]], dtype=np.double)
s2 = np.array([[0, 0],
               [2, 1],
               [0, 1],
               [0, .5],
               [0, 0]], dtype=np.double)
sa = subsequence_alignment(s1, s2)
match = sa.best_match()
startidx, endidx = match.segment

I got the error **The compiled dtaidistance C library is not available**

Now i followed the instructions as mentioned in Document. I got the below error.

>>> dtw.try_import_c(verbose=True)
Cannot import OMP-based library (dtw_cc_omp)
Cannot import Numpy-based library (dtw_cc_numpy)

Not all libraries are available in your installation. Share the following information when submitting a bug report:
- Cannot import OMP-based library (dtw_cc_omp)
- cannot import name 'dtw_cc_omp' from 'dtaidistance' (C:\Users\ujjuriv\AppData\Local\Programs\Python\Python38\lib\site-packages\dtaidistance\__init__.py)
- Cannot import Numpy-based library (dtw_cc_numpy)
- cannot import name 'dtw_cc_numpy' from 'dtaidistance' (C:\Users\ujjuriv\AppData\Local\Programs\Python\Python38\lib\site-packages\dtaidistance\__init__.py)
- System information:
  namespace(cache_tag='cpython-38', hexversion=50856176, name='cpython', version=sys.version_info(major=3, minor=8, micro=0, releaselevel='final', serial=0))
Additionally, you can rerun the compilation from source or pip install in verbose mode:
pip install -vvv --upgrade --force-reinstall --no-deps --no-binary :all: dtaidistance

Now I tried with below command 
pip install -vvv --upgrade --force-reinstall --no-deps --no-binary :all: dtaidistance

I observed that subsequence folder got deleted and observed the below error. seems dtaidistance version moved to 2.2.1 instead 2.2.5

    byte-compiling c:\python37\Lib\site-packages\dtaidistance\__init__.py to __init__.cpython-37.pyc
    running install_egg_info
    Copying dtaidistance.egg-info to c:\python37\Lib\site-packages\dtaidistance-2.2.1-py3.7.egg-info
    running install_scripts
    writing list of installed files to 'C:\Users\kattupd\AppData\Local\Temp\pip-record-bar5p7b0\install-record.txt'
    Installed the plain Python version of the package.
    If you need the C extension, try reinstalling.
    Running setup.py install for dtaidistance ... done
WARNING: Ignoring invalid distribution -taidistance (c:\python37\lib\site-packages)
Successfully installed dtaidistance-2.2.1
WARNING: Ignoring invalid distribution -taidistance (c:\python37\lib\site-packages)
WARNING: Ignoring invalid distribution -taidistance (c:\python37\lib\site-packages)
Removed dtaidistance from https://files.pythonhosted.org/packages/d6/ae/3b33bb905c018e7d6782652c3277f48003bfb380c22412fbe50ef48a5af3/dtaidistance-2.2.5.tar.gz#sha256=a34f8f8b3ba6ba7fa1be91f93266d16319d8da67d8dbe3ec02572f0b8cc9f0da from build tracker 'C:\\Users\\kattupd\\AppData\\Local\\Temp\\pip-req-tracker-46okpejk'
Removed dtaidistance from https://files.pythonhosted.org/packages/bf/e1/ed259da0bd1930a1650385251ab647f73bb34c98908f71d387c56c8d18de/dtaidistance-2.2.2.tar.gz#sha256=70656500645cd7fda4dc43ce62aee96e032631b28c8ae3503b3150a79ff449a1 from build tracker 'C:\\Users\\kattupd\\AppData\\Local\\Temp\\pip-req-tracker-46okpejk'
Removed dtaidistance from https://files.pythonhosted.org/packages/3f/7a/de333738ed533cf57f6d76981f075f8b30d919cc73048f16bb089bc12052/dtaidistance-2.2.4.tar.gz#sha256=c7d044a99e7999a00d12013b08d8bad5060b7d49fc0d528a0a81f9977607a29e from build tracker 'C:\\Users\\kattupd\\AppData\\Local\\Temp\\pip-req-tracker-46okpejk'
Removed dtaidistance from https://files.pythonhosted.org/packages/b6/9a/514c444f0a1af6b05968b531dcbe88875b5c9e8ced9833d01eab898a16d3/dtaidistance-2.3.1.tar.gz#sha256=9f3dfcf09288e42bbc73a184d1a31cb99466d08cf446e9f505174c738542b33e from build tracker 'C:\\Users\\kattupd\\AppData\\Local\\Temp\\pip-req-tracker-46okpejk'
Removed dtaidistance from https://files.pythonhosted.org/packages/fd/9b/b5f69a8837e771624ced09a3929dae4d0156f18b5e89b7f3b715795b5de7/dtaidistance-2.2.3.tar.gz#sha256=5b50fe4c5e2ec9ce493669b49a021f4797cf642395498dd106079bcbf06fbabf from build tracker 'C:\\Users\\kattupd\\AppData\\Local\\Temp\\pip-req-tracker-46okpejk'
Removed build tracker: 'C:\\Users\\kattupd\\AppData\\Local\\Temp\\pip-req-tracker-46okpejk'

Anyone can guide me to resolve the issues and use the subsequence module.

**Comment by wannesm** [comment]
I have updated the pypi version to include subsequences (which also work without the C extension). The installer should now be better at including Numpy into the compilation.

The C extension is to provide faster versions of the algorithm. Thanks for sharing the output. Unfortunately that's not the part that is needed to debug. Maybe try this variation: `pip install -v --upgrade --force-reinstall --no-deps --no-binary dtaidistance dtaidistance` and look at the output starting from `Compiler type:` and ending with `installing to build`.

**Comment by wannesm** [comment]
I assume this issue is resolved.
For other compilation problems, please start a new issue.
