### ISSUE TITLE
Is it possible to somehow edit the kmeans function so that we can use a sakoe chiba band parameter in it? 

### ISSUE THREAD

**Issue by StefanR44** [wannesm/dtaidistance#141]
Basically I am looking for a way to customize KMeans so that we can use the sakoe chiba band of DTW in it. But somehow i cannot find any DTW being used in this library? 

Please guide me

**Comment by wannesm** [comment]
Kmeans works with Dynamic Barycenter Averaging which is based on DTW.

You can pass a dictionary to `dists_options` which will be used to call the `distance` method. Thus think `distance(a, b, **dists_options)`.
