### ISSUE TITLE
Cluster function problem

### ISSUE THREAD

**Issue by colindying** [wannesm/dtaidistance#142]
I use the following command to perform clustering， but the program cannot finish

![image](https://user-images.githubusercontent.com/37111966/146634043-0136c056-9be9-41e8-a1bd-28409919f697.png)

**Comment by colindying** [comment]
the program didnot finish， but it should be running for a short time，what happened？

**Comment by wannesm** [comment]
The input data is a not supported combination of data types. A matrix is only supported if it contains numerical values directly, and in this case it is a matrix of size 1x4 with four lists as entries. See the examples in https://dtaidistance.readthedocs.io/en/latest/usage/dtw.html#dtw-between-multiple-time-series for a correct way of providing input.

I've updated the function to end, even if the input datatype is not as expected.
