### ISSUE TITLE
results are not correct!!!

### ISSUE THREAD

**Issue by Pranay144** [wannesm/dtaidistance#148]
1.  disjoint1
![newplot (4)](https://user-images.githubusercontent.com/45161803/148761288-e6eec4d9-5c32-45c4-aa36-44aab3a793f2.png)
2.  disjoint2
![newplot (5)](https://user-images.githubusercontent.com/45161803/148761290-53ec8e77-1749-4115-a737-94da4b8cdfe1.png)
3.  double_top
![newplot (3)](https://user-images.githubusercontent.com/45161803/148761293-f520ef2d-b93d-4c02-b911-6d79160a4b24.png)

so, 

dis = dtw.distance(disjoint1,disjoint2)
# output :  dis = 0.141

dis = dtw.distance(disjoint1,double_top)
# output : dis = 0.029

why distance between disjoint1 and disjoint2 is greater than distance between disjoint1 and double top?

by looking its obvious that the distance should be greater! or am I doing something wrong?

**Comment by wannesm** [comment]
This is an expected result. The range of disjoint1 is closer to double_tops than to disjoint2 (and smaller than the difference in shape). If you want to compare shapes you need to normalize. See the documentation: https://dtaidistance.readthedocs.io/en/latest/usage/dtw.html#dtw-based-on-shape-z-normalization

**Comment by Pranay144** [comment]
Thanks, @wannesm .
