### ISSUE TITLE
Clustering example not running

### ISSUE THREAD

**Issue by fredthedead** [wannesm/dtaidistance#15]
Trying to run the example from the documentation:

```
# Custom Hierarchical clustering
model1 = clustering.Hierarchical(dtw.distance_matrix_fast, {})
# Keep track of full tree by using the HierarchicalTree wrapper class
model2 = clustering.HierarchicalTree(model1)
# You can also pass keyword arguments identical to instantiate a Hierarchical object
model2 = clustering.HierarchicalTree(dists_fun=dtw.distance_matrix_fast, dists_options={})
# SciPy linkage clustering
model3 = clustering.LinkageTree(dtw.distance_matrix_fast, {})
cluster_idx = model3.fit(series)
```

and getting an error for any of the proposed models:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-38-4bb92754361e> in <module>()
      2 model1 = clustering.Hierarchical(dtw.distance_matrix_fast, {})
      3 # Keep track of full tree by using the HierarchicalTree wrapper class
----> 4 model2 = clustering.HierarchicalTree(model1)
      5 # You can also pass keyword arguments identical to instantiate a Hierarchical object
      6 model2 = clustering.HierarchicalTree(dists_fun=dtw.distance_matrix_fast, dists_options={})

/Users/fred/anaconda/lib/python2.7/site-packages/dtaidistance/clustering.pyc in __init__(self, model, **kwargs)
    388         else:
    389             self._model = model
--> 390         super().__init__(**kwargs)
    391         self._model.max_dist = np.inf
    392 

TypeError: super() takes at least 1 argument (0 given)
```

**Comment by adriangrepo** [comment]
I have the same issue when running clustering example, dtaidistance compiled from source.

`series = [
    np.array([0, 0, 1, 2, 1, 0, 1, 0, 0], dtype=np.double),
    np.array([0.0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0]),
    np.array([0.0, 0, 1, 2, 1, 0, 0, 0])]`

`# Custom Hierarchical clustering
model1 = clustering.Hierarchical(dtw.distance_matrix_fast, {})
# Augment Hierarchical object to keep track of the full tree
model2 = clustering.HierarchicalTree(model1)
# SciPy linkage clustering
model3 = clustering.LinkageTree(dtw.distance_matrix_fast, {})
cluster_idx = model3.fit(series)`

`The compiled dtaidistance C library is not available.
See the documentation for alternative installation options.
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-22-ce25e139c3dc> in <module>()
      5 # SciPy linkage clustering
      6 model3 = clustering.LinkageTree(dtw.distance_matrix_fast, {})
----> 7 cluster_idx = model3.fit(series)

~/.virtualenvs/ts/lib/python3.6/site-packages/dtaidistance/clustering.py in fit(self, series)
    445         idx = 0
    446         for r in range(len(series) - 1):
--> 447             dists_cond[idx:idx + len(series) - r - 1] = dists[r, r + 1:]
    448             idx += len(series) - r - 1
    449 

TypeError: 'NoneType' object is not subscriptable`

**Comment by wannesm** [comment]
The library is developed for Python 3.
