### ISSUE TITLE
Can we change the color of wrapping path?

### ISSUE THREAD

**Issue by ZihanChen1995** [wannesm/dtaidistance#157]
Hi, thank you so much for the great library! May I ask can we change the color of the wrapping paths? Using the example in official guidance:

```
s1 = np.array([0., 0, 1, 2, 1, 0, 1, 0, 0, 2, 1, 0, 0])
s2 = np.array([0., 1, 2, 3, 1, 0, 0, 0, 2, 1, 0, 0, 0])
path = dtw.warping_path(s1, s2)
dtwvis.plot_warping(s1, s2, path, filename="warp.png")
```

The defaulted color of the wrapping path is orange. But I guess it is too light when printing out. **May I ask is there any way that we can change the color of the path (e.g., green)?** Thank you so much in advance!

**Comment by wannesm** [comment]
Currently not. You'd have to change the line settings in this line: https://github.com/wannesm/dtaidistance/blob/47a596accaa9742b672b474e176247ca273d442b/dtaidistance/dtw_visualisation.py#L127
making this accessible via the arguments is something we can consider for a next release.

**Comment by ZihanChen1995** [comment]
Got it! Thank you for the reply @wannesm . Really appreciate!
