### ISSUE TITLE
exclude single point to multiple points warping?

### ISSUE THREAD

**Issue by bartmch** [wannesm/dtaidistance#160]
I'm first creating the matrix:
`d, paths = dtw.warping_paths(s1_diff, s2_diff, window=30, use_pruning=True)`
Then I'm calculating the best path and plotting the warping between the two time-series:
```
best_path = dtw.best_path(paths)
dtwvis.plot_warping(s1.values, s2.values, best_path)
```
I'm getting the following graph:
<img width="1083" alt="image" src="https://user-images.githubusercontent.com/10415569/154924914-be023b8c-6945-4c74-9ec7-0bed991d7dfe.png">
Is there a way to exclude a single point to multiple points warping like the zoomed-in part below? In this example, you can see three single points from the upper graph being warped on multiple points of the lower graph. There's also one single point from the lower graph warped on multiple points of the upper graph.
<img width="339" alt="image" src="https://user-images.githubusercontent.com/10415569/154925134-028c5fb0-29ee-480a-b535-290c66f343b1.png">
Ideally, I'd be looking at **almost** constant warping paths as seen in the zoomed-in part below.
<img width="228" alt="image" src="https://user-images.githubusercontent.com/10415569/154925570-1ea17487-57a8-4b42-b62e-610d0e40aabb.png">

This question might be ill-defined so apologies for that.

**Comment by wannesm** [comment]
This would be the `window` and or `penalty` options to steer this. But there is not argument that can put an exact value to this (this would violate the properties used by the dynamic programming).
Using differencing first is another approach to reduce this effect if the absolute values cause this.
