### ISSUE TITLE
Support for multi-dimensionsal DTW (ndim variants) subsequence matching?

### ISSUE THREAD

**Issue by rytheranderson** [wannesm/dtaidistance#161]
Hello all,

I was wondering if support for subsequence matching with multi-dimensional time series could be quickly added to the subsequence alignment tools? If not, would modifying the existing SubsequenceAlignment class to use dtw_ndim.warping_paths (at line 126, https://github.com/wannesm/dtaidistance/blob/0b2dea2ecaf22e0781009ebf181a5bb16d6b425e/dtaidistance/subsequence/dtw.py#L126) be the correct procedure?

**Comment by wannesm** [comment]
You're in the right direction and it's indeed not very difficult, but it's not that quick (thus no theoretical limitations, just lack of time to implement and test it). The main obstacle is that support for multiple psi values is required and that is not yet implemented for the multi-dimensional versions of `warping_paths`.

**Comment by rytheranderson** [comment]
Thanks for the info, do you mean that the multi-dimensional version of warping_paths cannot use psi as a 4-tuple? Passing a 4-tuple does not seem to break the multi-dimensional warping_paths function, but is it not handled correctly?

**Comment by wannesm** [comment]
You were right that it was actually easier than I thought. We did already implement most of the functionality (it was another bug that was just fixed in another issue). The master branch now supports multi-dimensional subsequence search.

**Comment by rytheranderson** [comment]
Great, thanks!
