### ISSUE TITLE
Support for ndim of warping_path in C

### ISSUE THREAD

**Issue by hidex520** [wannesm/dtaidistance#163]
Hello all,
It looks something wrong in C version for handling ndim of warping_path. Is it a known issue or not? Thank you.
p.s. z_normQ/z_normC shape[0] is 30, shape[1] is 3

d, paths = dtw_ndim.warping_paths(z_normQ, z_normC,use_c=True)
Traceback (most recent call last):
  File "<ipython-input-4-6c0fb53cae22>", line 1, in <module>
    d, paths = dtw_ndim.warping_paths(z_normQ, z_normC,use_c=True)
  File "D:\Anaconda3\lib\site-packages\dtaidistance\dtw_ndim.py", line 281, in warping_paths
    return dtw.warping_paths(*args, use_ndim=True, **kwargs)
  File "D:\Anaconda3\lib\site-packages\dtaidistance\dtw.py", line 411, in warping_paths
    return warping_paths_fast(s1, s2, window=window, max_dist=max_dist, use_pruning=use_pruning,
  File "D:\Anaconda3\lib\site-packages\dtaidistance\dtw.py", line 571, in warping_paths_fast
    d = dtw_cc.warping_paths_ndim(dtw, s1, s2, psi_neg, ndim, **settings_kwargs)

  File "dtaidistance\dtw_cc.pyx", line 344, in dtaidistance.dtw_cc.warping_paths_ndim

ValueError: Buffer has wrong number of dimensions (expected 1, got 2)

**Comment by wannesm** [comment]
Can you share a reproducible example that triggers this error?

**Comment by hidex520** [comment]
My environment: Windows 10 64bit + Anaconda3
Python 3.8.3
Cython version 0.29.24
Compiler type: mingw32
```
import numpy
import numpy as np
from dtaidistance import dtw_ndim, dtw
from dtaidistance import dtw_visualisation as dtwvis

test_A=[[ 2.65598039,  0.93622549, -0.04169118],
       [ 2.02625   ,  0.965625  , -0.050625  ],
       [ 0.41973039,  0.85968137,  0.38970588],
       [ 0.3669697 , -0.03221591,  0.09734848],
       [ 0.68905971, -0.65101381, -0.70944742],
       [ 0.14142316, -0.81769481, -0.44556277],
       [ 0.2569697 , -0.6330303 , -0.35503788],
       [-0.39339286,  0.02303571, -0.48428571],
       [-0.8275    , -0.02125   , -0.0325    ],
       [-0.65293269, -0.29504808,  0.30557692]]

test_B=[[-1.54647436e+00, -3.76602564e-01, -8.58974359e-01],
       [-1.14283907e+00, -8.50961538e-01, -5.42974022e-01],
       [-4.86715587e-01, -8.62221660e-01, -6.32211538e-01],
       [ 3.54672740e-02, -4.37500000e-01, -4.41801619e-01],
       [ 7.28618421e-01, -4.93421053e-03, -8.90625000e-01],
       [ 1.03525641e+00,  1.25000000e-01, -8.50961538e-01],
       [ 5.24539474e-01,  1.07828947e-01, -3.99375000e-01],
       [ 5.04464286e-01,  3.76275510e-01, -6.74744898e-01],
       [ 1.20897959e+00,  1.10793367e+00, -1.45681122e+00],
       [ 8.70535714e-01,  8.73724490e-01, -1.01275510e+00]]

test_A = np.array(test_A)
test_B = np.array(test_B)

res = dtw_ndim.distance(test_A,test_B,use_c=True)
```
> it's OK when I run in python version
```
**d, paths = dtw_ndim.warping_paths(test_A, test_B)**
best_path = dtw.best_path(paths)
dtwvis.plot_warpingpaths(test_A, test_B, paths, best_path)
```
> ValueError: Buffer has wrong number of dimensions (expected 1, got 2)
> run it when set use_c as True
```
d, paths = dtw_ndim.warping_paths(test_A, test_B,use_c=True)
```

**Comment by LarsHaalck** [comment]
I had the same issue and the referenced commit fixes it for me. I can submit a PR but I'm not a Cython expert and unsure if this is correct.

**Comment by wannesm** [comment]
Thanks, this was indeed a signature that was not correctly updated after a change.
There were a few things missing (or too much) in the update mentioned by @LarsHaalck for our envisioned structured but it was a good start (I've credited you in the authors file).
A new version is available in the master branch for you to try.
