### ISSUE TITLE
sed: can't read s/^typedef when using make float

### ISSUE THREAD

**Issue by tommedema** [wannesm/dtaidistance#186]
Recently I started getting this on an ARM machine:

```
git clone https://github.com/wannesm/dtaidistance.git && cd dtaidistance
cd dtaidistance/jinja && make float
```

It errors out:

```
Generating: dtw_cc_omp.pyx
Changed: dtaidistancec_globals.jinja.pxd
python3 generate.py --seqt=float dtaidistancec_globals.pxd
Generating: dtaidistancec_globals.pxd
Changed: dtw_cc.jinja.pxd
python3 generate.py --seqt=float dtw_cc.pxd
Generating: dtw_cc.pxd
cp dtw_cc.pyx ../
cp dtw_cc_omp.pyx ../
cp dtaidistancec_globals.pxd ../
cp dtw_cc.pxd ../
Changed: ed_cc.jinja.pyx
python3 generate.py --seqt=float ed_cc.pyx
Generating: ed_cc.pyx
cp ed_cc.pyx ../
sed -i '' 's/^typedef .* seq_t;$/typedef double seq_t;/g' ../lib/DTAIDistanceC/DTAIDistanceC/dd_globals.h
sed: can't read s/^typedef .* seq_t;$/typedef double seq_t;/g: No such file or directory
make: *** [Makefile:27: generate] Error 2
```

**Comment by tommedema** [comment]
This is because the `sed` command has different syntax on MacOS vs Unix.

On MacOS the `-i ''` seems to be required where on Unix it should not be present for the command to work.

See also https://unix.stackexchange.com/questions/13711/differences-between-sed-on-mac-osx-and-other-standard-sed.

**Comment by tommedema** [comment]
I went ahead and removed `-i ''` from the makefile but when running dtaidistance I now get this error:

`ValueError: Buffer dtype mismatch, expected 'seq_t' but got 'float'`

**Comment by wannesm** [comment]
I did indeed only consider macos for this. Thanks for the notification and suggestions. I added a few lines to the makefile to detect the OS to solve it. 
At one point I should look into adding autoconf or something similar to deal with all the platform dependent constraints :-)

**Comment by wannesm** [comment]
I removed the `sed` command and included changing this one line in the Python script that generates all the files. This way there is no platform dependent code anymore.
