### ISSUE TITLE
How is the DTW calculated between 3D time series?

### ISSUE THREAD

**Issue by Waterkin** [wannesm/dtaidistance#188]

**Comment by wannesm** [comment]
dtaidistance has support for dependent and independent multi-dimensional time series warping:
https://dtaidistance.readthedocs.io/en/latest/usage/dtw.html#multi-dimensionsal-dtw

If you want to read more about this, see for example https://www.cs.ucr.edu/~eamonn/Multi-Dimensional_DTW_Journal.pdf
