### ISSUE TITLE
conda-forge osx-arm64 build

### ISSUE THREAD

**Issue by kbrownlees** [wannesm/dtaidistance#190]
Apologies if this is the wrong place to request this. But it would be great to understand what would be involved in adding a osx-arm64 build to conda-forge?

Many thanks for the great package!

**Comment by wannesm** [comment]
The main reason why it is not there might be a lack of knowledge on our end. @m-rossi has been generously keeping the Conda version up to date. If we can find some time, we can investigate whether it is simply adding the architecture to the script or more is involved (e.g. for github actions, arm64 is not yet available and we need to compile locally).

For the package itself, it is compatbile with osx-arm64 as this is one of the architectures we use ourselves. Thus if you have the xcode tools (and openmp) installed, it should work from source. Or via pypi you can also download a precompiled version for Python 3.10 and macos 12 (we can add other python versions if useful).

**Comment by m-rossi** [comment]
It can be as simple as adding the architecture. I need to check if all requirements are already available on `osx-arm64`

**Comment by m-rossi** [comment]
Looks good, will try to add an [Apple Silicon builds](https://conda-forge.org/docs/maintainer/knowledge_base.html#apple-silicon-builds)

**Comment by m-rossi** [comment]
@kbrownlees builds for `osx-arm64` should be available now.

**Comment by wannesm** [comment]
Wow, this was fast. Thanks @m-rossi !

**Comment by kbrownlees** [comment]
Amazing! Thank you for the incredible turn around @m-rossi & @wannesm!

I was able to successfully install it from conda-forge on my M1 mac & https://anaconda.org/conda-forge/dtaidistance confirms it is not available.
