### ISSUE TITLE
Broken figures on readthedocs

### ISSUE THREAD

**Issue by dizcza** [wannesm/dtaidistance#199]
It seems that no figure is displayed on readthedocs.

Check out the clustering module, for example: https://dtaidistance.readthedocs.io/en/latest/usage/clustering.html
```
<div class="figure">
<img alt="Clustering hierarchy" src="https://people.cs.kuleuven.be/wannes.meert/dtw/hierarchy.png?v=2">
</div>
```
But I don't see any images.

**Comment by wannesm** [comment]
Strange, for me they show. Can you see the images when openen the url directly? https://people.cs.kuleuven.be/~wannes.meert/dtw/hierarchy.png?v=2

**Comment by dizcza** [comment]
all right,
traffic from Ukraine is blocked.
I'm able to reach the page under VPN only.

**Comment by wannesm** [comment]
That is annoying, yes. On our side there is no block, so unsure where this comes from. But we will look into moving the images to the readthedocs servers.
