### ISSUE TITLE
How to solve C library not available

### ISSUE THREAD

**Issue by tylermanning** [wannesm/dtaidistance#20]
I installed this package and tried the fast implementation of the DTW but I get:

> The compiled dtaidistance C library is not available.
> See the documentation for alternative installation options

How can I rectify this? I have Cython installed and all other dependencies. The docs don't point to any other specific installations necessary. Thanks,

**Comment by wannesm** [comment]
Something must have gone wrong when trying to compile the Cython extension. Did you get any error messages when installing the package? Can you post the log?

**Comment by tylermanning** [comment]
I did not get any error messages or warnings when installing `dtaidistance` or installing Cython. (i have the other packages installed already). I am not sure what log you are referring to.

**Comment by wannesm** [comment]
If you are using pip you can increase the verbosity level and try reinstalling: 
``pip install --vvv --upgrade --force-reinstall dtaidistance``

**Comment by tylermanning** [comment]
The command you gave does not work but it works without the `--vvv` option. I get the following error:

> Installing collected packages: numpy, cython, dtaidistance
>   Found existing installation: numpy 1.15.0
>     Uninstalling numpy-1.15.0:

> Could not install packages due to an EnvironmentError: [Errno 39] Directory not empty: 'core'

**Comment by wannesm** [comment]
It is only one dash ``-vvv``. This looks like a problem with the package manager. Maybe try upgrading pip?

**Comment by tylermanning** [comment]
Thanks that fixed it but I get the same error. My PIP version is 18.1 which I believe is latest.

**Comment by wannesm** [comment]
It appears your installation fails to delete the existing ``core`` folder of numpy. This could be a permission problem. Did you install with sudo and are now running without sudo?

**Comment by mike-schwarz** [comment]
I am also having this issue and have not been able to get it resolved by downgrading to older versions of Cython and numpy. I have also tried manually installing dtw-c. According to the source code, the "The compiled dtaidistance C library is not available." gets thrown when dtw-c is not available. Any help with this would be much appreciated!

**Comment by jdv12** [comment]
Hey having the same issue.  Tried everything listed here to no avail.  Has anyone else been able to resolve this?

**Comment by TCACastelijns** [comment]
I'm having the same issues right now. @wannesm: Do you have any idea to resolve this issue?

**Comment by CarioniStefano** [comment]
Same problem here!

**Comment by MariaKapala** [comment]
I had a similar issue.
Unfortunately, the wonderful error handling in this library is obscuring the underling errors.
In my case, I was missing the LLVM's OpenMP runtime library.

If you are on macOS, you can install it via brew.

> brew install libomp

**Comment by rimil1994** [comment]
Same problem here. Can anyone please provide any solution

**Comment by Molugan** [comment]
Same issue her too.

**Comment by wannesm** [comment]
The latest version has a `dtw.try_import_c()` function that will retry to import the c-library and print the error message if there is a problem. Hopefully this will help you identify the problem with the library (the other one is still to install it using `pip install -vvv --upgrade --force-reinstall dtaidistance`).

**Comment by jmtatsch** [comment]
Strange, when installing via pip it does not even attempt to build the cython part

```
Installing collected packages: cython, dtaidistance
  Attempting uninstall: cython
    Found existing installation: Cython 0.29.21
    Uninstalling Cython-0.29.21:
      Created temporary directory: /tmp/pip-uninstall-9axh9h1w
      Removing file or directory /home/tatsch/.virtualenvs/error_pattern_recognition/bin/cygdb
      Removing file or directory /home/tatsch/.virtualenvs/error_pattern_recognition/bin/cython
      Removing file or directory /home/tatsch/.virtualenvs/error_pattern_recognition/bin/cythonize
      Created temporary directory: /home/tatsch/.virtualenvs/error_pattern_recognition/lib/python3.8/site-packages/~ython-0.29.21.dist-info
      Removing file or directory /home/tatsch/.virtualenvs/error_pattern_recognition/lib/python3.8/site-packages/Cython-0.29.21.dist-info/
      Created temporary directory: /home/tatsch/.virtualenvs/error_pattern_recognition/lib/python3.8/site-packages/~ython
      Removing file or directory /home/tatsch/.virtualenvs/error_pattern_recognition/lib/python3.8/site-packages/Cython/
      Created temporary directory: /tmp/pip-uninstall-_g0i2o4u
      Removing file or directory /home/tatsch/.virtualenvs/error_pattern_recognition/lib/python3.8/site-packages/__pycache__/cython.cpython-38.pyc
      Created temporary directory: /tmp/pip-uninstall-3q69fth8
      Removing file or directory /home/tatsch/.virtualenvs/error_pattern_recognition/lib/python3.8/site-packages/cython.py
      Created temporary directory: /home/tatsch/.virtualenvs/error_pattern_recognition/lib/python3.8/site-packages/~yximport
      Removing file or directory /home/tatsch/.virtualenvs/error_pattern_recognition/lib/python3.8/site-packages/pyximport/
      Successfully uninstalled Cython-0.29.21

  changing mode of /home/tatsch/.virtualenvs/error_pattern_recognition/bin/cygdb to 775
  changing mode of /home/tatsch/.virtualenvs/error_pattern_recognition/bin/cython to 775
  changing mode of /home/tatsch/.virtualenvs/error_pattern_recognition/bin/cythonize to 775
  Attempting uninstall: dtaidistance
    Found existing installation: dtaidistance 2.1.2
    Uninstalling dtaidistance-2.1.2:
      Created temporary directory: /home/tatsch/.virtualenvs/error_pattern_recognition/lib/python3.8/site-packages/~taidistance-2.1.2.dist-info
      Removing file or directory /home/tatsch/.virtualenvs/error_pattern_recognition/lib/python3.8/site-packages/dtaidistance-2.1.2.dist-info/
      Created temporary directory: /home/tatsch/.virtualenvs/error_pattern_recognition/lib/python3.8/site-packages/~taidistance
      Removing file or directory /home/tatsch/.virtualenvs/error_pattern_recognition/lib/python3.8/site-packages/dtaidistance/
      Successfully uninstalled dtaidistance-2.1.2

Successfully installed cython-0.29.21 dtaidistance-2.1.2
Removed build tracker: '/tmp/pip-req-tracker-4oclumea'
```

with
```
pip3 -V                                                                                                                                         
pip 20.3.1 from /home/tatsch/.virtualenvs/error_pattern_recognition/lib/python3.8/site-packages/pip (python 3.8)
```

**Comment by jmtatsch** [comment]
Must have been something bad in my cache.
Reinstalling with:
`pip install -vvv --upgrade --no-cache-dir --force-reinstall dtaidistance`
seemed to have triggered the cythonization correctly.

**Comment by jantmueller** [comment]
@jmtatsch thank you. the additional "--no-cache-dir" solved my problem as well.

**Comment by ywu36** [comment]
If you look into the error in installation, you'll notice that it says 'error: 'for' loop initial declarations are only allowed in C99 mode".

So before you run:` pip install -vvv --upgrade --no-cache-dir --force-reinstall dtaidistance,
`
you need to run:

**export CFLAGS='-std=c99'**

This line plays the magic for me.

**Comment by nnbaokhang** [comment]
> pip install -vvv --upgrade --force-reinstall dtaidistance

**Comment by dayanand4u** [comment]
Hi I am using windows and python 3.7.8 version. Could up please guide me resolve the issue. 

I have installed dtaidistance using pip. When I executed sample code for subsequence, I am facing issue as "c the compiled dtaidistance c library is not available".

Could you please guide me how to resolve it.
May I know the clear installation details. I am unable to find it documentation.

**Comment by kosuke-zhang** [comment]
> If you look into the error in installation, you'll notice that it says 'error: 'for' loop initial declarations are only allowed in C99 mode".
> 
> So before you run:`pip install -vvv --upgrade --no-cache-dir --force-reinstall dtaidistance,` you need to run:
> 
> **export CFLAGS='-std=c99'**
> 
> This line plays the magic for me.

fix gcc compile error successfully!
