### ISSUE TITLE
Python 3.12 / NumPy 1.26 support

### ISSUE THREAD

**Issue by m-rossi** [wannesm/dtaidistance#201]
[conda-forge](https://conda-forge.org) recently [started the migration to Python 3.12](https://conda-forge.org/docs/user/announcements.html#python-3-12-migration-and-python-3-11-by-default), also for `dtaidistance` in https://github.com/conda-forge/dtaidistance-feedstock/pull/15. After I figured out to limit `cython <3.0` (with hints from https://github.com/wannesm/dtaidistance/pull/198) to fix most issues for Python versions below 3.12, there are still some issues left I do not understand, you may have a look at those failing logs?

**Comment by m-rossi** [comment]
Seems it is fixed with your latest release, closing.

**Comment by wannesm** [comment]
Indeed. I forgot to mention. A colleague made the code compatible with cython 3. Thanks for following up.
