### ISSUE TITLE
Memory freeing issue

### ISSUE THREAD

**Issue by Huii** [wannesm/dtaidistance#21]
I'm using Python 3.6 (with Anaconda) on a Windows 8.1 and a Windows 10 machine at work. I'm dealing with rather large data sets (roughly 10 data sets with 10,000 sequences consisting of 3,000 samples each). dtaidistance is working as expected but whenever I set the "use_c" parameter of the "distance" function, I can observe in the task-manager that the corresponding Python process slowly eats up all available RAM.

If I want to run datidistance on several data sets overnight, it regularly simply crashes after all my available RAM (roughly 32 GB) has been used.

Could it be possible that somehow the memory isn't freed again properly after it has been used?

**Comment by wannesm** [comment]
There was indeed a memory leak if you set some early stopping criterion (e.g. max dist). Fixed in commit 3d48138b01bf2f320eb92b26695fdf9173524bbc. Does this solve your problem?

**Comment by Huii** [comment]
That seems to have fixed it. Thank you very much again.

**Comment by wannesm** [comment]
Thanks for the notification and testing it.
