### ISSUE TITLE
Compatibility with Numpy>=2.0.0

### ISSUE THREAD

**Issue by yamhs** [wannesm/dtaidistance#216]
This package is currently not compatible with NumPy v2.0. To avoid issues, please constrain the dependency to numpy <2.0.0. Alternatively, consider recompiling the package with the latest version of NumPy.

**Comment by wannesm** [comment]
The current release is compatible with numpy 2. The precompiled version is with numpy <2 though as that was still the default when we released. Is that what you mean? Using pip with no-binary should fix it for now if you want to use numpy 2 (but requires compiling). Or use Conda where we haven both versions precompiled.

**Comment by yamhs** [comment]
Thanks for your quick response. Yes exactly, the compatibility issue is with the compiled fast C implementation. But even with the no-binary option or compiling from source I get the same error:

`A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.`

**Comment by yamhs** [comment]
Thanks for your quick response.

For poetry users, you need 

```
# poetry.toml

[installer]
no-binary = ["dtaidistance"]
```
