### ISSUE TITLE
dtw.distance_fast() return best_path

### ISSUE THREAD

**Issue by TFelgueira** [wannesm/dtaidistance#22]
Is it possible for the C implementation of dtw distance to return not only the final distance but also the best_path or all paths? Because besides having the final distance, I would be interested in analysing the individual distances over time. Would that be possible?

**Comment by wannesm** [comment]
There is now a ``dtw.warping_paths_fast`` function that calls the ``dtw_c.warping_paths_nogil`` function that does part of this. The ``best_path`` function is a python function but this operation is linear whereas computing the warping paths function is quadratic.
