### ISSUE TITLE
ValueError: 'dtaidistance/dtw_c.pyx' doesn't match any files

### ISSUE THREAD

**Issue by Huii** [wannesm/dtaidistance#23]
I'm currently facing two issues. The first is that I'm unable to recompile the source code after updating the repository. Whenever I attempt to do this via

`C:\pythoToMyPython\python.exe D:\pathToDtaidistance\dtaidistance\setup.py build_ext --inplace`
on my Windows (10) machine, I get the following message:

> Traceback (most recent call last):
>   File "D:\pathToDtaidistance\dtaidistance\setup.py", line 123, in <module>
>     extra_link_args=extra_link_args)])
>   File "D:\PathToMyAnaconda\Anaconda\lib\site-packages\Cython\Build\Dependencies.py", line 897, in cythonize
>     aliases=aliases)
>   File "D:\PathToMyAnaconda\Anaconda\lib\site-packages\Cython\Build\Dependencies.py", line 777, in create_extension_list
>     for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
>   File "D:\PathToMyAnaconda\Anaconda\lib\site-packages\Cython\Build\Dependencies.py", line 102, in nonempty
>     raise ValueError(error_msg)
> ValueError: 'dtaidistance/dtw_c.pyx' doesn't match any files

That's strange because my dtaidistance folder contains a file named "dtw_c.pyx".

For the second issue, I will open a separate ticket.

**Comment by wannesm** [comment]
I think the setup.py file needs to be run from within the dtaidistance directory (thus where the setup.py file is). The paths are defined relatively from the setup.py parent directory (that's something that could be improved).

**Comment by Huii** [comment]
You're right. That did the trick. Thank you very much.
