### ISSUE TITLE
ValueError: Buffer dtype mismatch, expected 'double' but got 'short'

### ISSUE THREAD

**Issue by Huii** [wannesm/dtaidistance#24]
I'm trying to run your DTW implementation on data with values in the range of -2000 to 2000. If I normalize the data to a certain (usually much smaller) range first, I have no issues. However, whenever I attempt to run your code on the raw (i.e. unnormalized) data, I end up with the following message:

> ValueError: Buffer dtype mismatch, expected 'double' but got 'short'

The trace back is as follows:

> Traceback (most recent call last):
>   File "D:\PathToMyProject\testing.py", line 313, in myDTWFunction
>     myDistance = dtw.distance(a,b,use_c=True,window=w,max_dist=minimumDistance)
>   File "D:\PathToMyAnaconda\lib\site-packages\dtaidistance-1.1.3-py3.6-win-amd64.egg\dtaidistance\dtw.py", line 84, in distance
>     psi=psi)
>   File "D:\PathToMyAnaconda\lib\site-packages\dtaidistance-1.1.3-py3.6-win-amd64.egg\dtaidistance\dtw.py", line 196, in distance_fast
>     psi=psi)
>   File "dtaidistance\dtw_c.pyx", line 129, in dtaidistance.dtw_c.distance_nogil

I thought this might be an issue with some old code and I tried to recompile the most recent code from your repository, but I didn't succeed yet due to [this issue](https://github.com/wannesm/dtaidistance/issues/23).

P.S: I run the code on a Windows 10 machine.

**Comment by wannesm** [comment]
The (c-part of the) library expects a double floating point datatype. The raw data is of the short type (thus an integer) and needs to be cast first to double (a floating point).

For numpy, setting the dtype explicitly should work:
``s1 = np.array([0, 0, 1, 2, 1, 0, 1, 0, 0], dtype=np.double)``

For the stdlib array this would be:
``s1 = array.array('d',[0, 0, 1, 2, 1, 0, 1, 0, 0])``

ps: There is no technical reason why the library couldn't be made to also work for integers. It's simply a lack of time and no urgency for our applications.

**Comment by Huii** [comment]
Thank you very much. Transforming my input to double arrays worked. Maybe you should mention this somewhere in the documentation to avoid confusions in the future.

**Comment by wannesm** [comment]
It's already in the documentation but I've now tried to make it more clear and added it to the docstring. If I find some more time I might add a type test to the method.
