### ISSUE TITLE
Error in installation of dtaidistance

### ISSUE THREAD

**Issue by lokeshnagar123** [wannesm/dtaidistance#28]
**----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-5FU_xZ/dtaidistance/**

pip install dtaidistance
Collecting dtaidistance
  Using cached https://files.pythonhosted.org/packages/75/ad/458d751a5d4842e3f7aa0ad6f79ee0219683d0b28ebc0d882f4106436a10/dtaidistance-1.1.4.tar.gz
    Complete output from command python setup.py egg_info:
    /home/lokesh/.local/lib/python2.7/site-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/pip-build-5FU_xZ/dtaidistance/dtaidistance/dtw_c.pyx
      tree = Parsing.p_module(s, pxd, full_module_name)
    Compiling dtaidistance/dtw_c.pyx because it depends on /home/lokesh/.local/lib/python2.7/site-packages/Cython/Includes/numpy/__init__.pxd.
    [1/1] Cythonizing dtaidistance/dtw_c.pyx
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-5FU_xZ/dtaidistance/setup.py", line 139, in <module>
        with open('dtaidistance/__init__.py', 'r', encoding='utf-8') as fd:
    TypeError: 'encoding' is an invalid keyword argument for this function

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-5FU_xZ/dtaidistance/

**Comment by Huii** [comment]
I recently faced a similar problem.  Does this closed ticket help you out: https://github.com/wannesm/dtaidistance/issues/23  ?
