### ISSUE TITLE
how to reformat dense dendrogam plot

### ISSUE THREAD

**Issue by momonala** [wannesm/dtaidistance#30]
Is there a recommended way to reformat the dendogram plot if there are many time series? Mine is quite dense and hard to read. My code:

```python
im_name = 'pic.png'
cluster_model.plot(im_name, show_ts_label=names, show_tr_label=True)
ax.imshow(plt.imread(im_name))
```

Thanks! 

![image](https://user-images.githubusercontent.com/16393105/50694734-01c03780-103b-11e9-90ef-365896f9b39a.png)

**Comment by wannesm** [comment]
The solution is to create a figure that has a larger figsize and pas the axes to the plot method. Additionally you can change the margins to put the labels on different locations. See the example on https://dtaidistance.readthedocs.io/en/latest/usage/clustering.html
