### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by andmib** [wannesm/dtaidistance#32]
I am getting a memory error when trying to calculate DTW distances for a numpy matrix of 2.2 million series with 157 time points. I have 400 GB of RAM available, with < 10% of utilization, and immediately get the error when trying to run `dtw.distance_matrix_fast`. Here is the traceback:

```
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-64-51fa732ba330> in <module>
      2 dists = dtw.distance_matrix_fast(df_numpy, window=15,
      3                                  parallel=True,
----> 4                                  show_progress=True)
      5 dists[dists == np.inf] = 0
      6 dists = dists + dists.T - np.diag(np.diag(dists))

~/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/dtaidistance/dtw.py in distance_matrix_fast(s, max_dist, max_length_diff, window, max_step, penalty, psi, block, parallel, show_progress)
    449                            window=window, max_step=max_step, penalty=penalty, psi=psi,
    450                            block=block, parallel=parallel,
--> 451                            use_c=True, use_nogil=True, show_progress=show_progress)
    452 
    453 

~/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/dtaidistance/dtw.py in distance_matrix(s, max_dist, max_length_diff, window, max_step, penalty, psi, block, parallel, use_c, use_nogil, show_progress)
    367         if parallel:
    368             logger.info("Use parallel computation")
--> 369             dists = dtw_c.distance_matrix_nogil_p(s, **dist_opts)
    370         else:
    371             logger.info("Use serial computation")

~/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/dtaidistance/dtw_c.pyx in dtaidistance.dtw_c.distance_matrix_nogil_p()

~/anaconda3/envs/tf-gpu/lib/python3.6/site-packages/dtaidistance/dtw_c.pyx in dtaidistance.dtw_c.distance_matrix_nogil()

MemoryError: 
```

Any suggestions? Is it not feasible to run DTW on a dataset this large?

**Comment by wannesm** [comment]
I'd assume that the matrix containing the results is too large for memory. For large datasets, it's recommended to use a custom approach that does not need to keep all results in memory. E.g. use the DTW function as part of a distributed approach. But for such large datasets, a preprocessing step is probably required to partition the dataset and avoid some of the pairwise distance computations (this is not yet part of this package).

A back-of-the-enveloppe computation: 22m series results in ~22e6**2 / 2 pairwise distances. At 8 bytes (the double type) that is (22e6**2 / 2 * 8) / (1000**3) = 1,936,000 GB.
