### ISSUE TITLE
Parallel computation not work.

### ISSUE THREAD

**Issue by andmib** [wannesm/dtaidistance#33]
I'm running Ubuntu 18.04, and I compiled `dtaidistance` from GitHub. When logging `info` level, it's confirmed that the C libraries installed and parallel computation is enabled, but htop shows a single core running when running `model = clustering.LinkageTree(dtw.distance_matrix_fast, {'parallel':True})`. Any thoughts on why parallelization isn't working? Or how to debug it?

```
INFO:be.kuleuven.dtai.distance:Computing distances
INFO:be.kuleuven.dtai.distance:Compute distances in pure C
INFO:be.kuleuven.dtai.distance:Use parallel computation
```

**Comment by wannesm** [comment]
The parallel computation requires OpenMP. This is only automatically activated on Mac for recent versions of Clang. We have added a flag to setup.py to force to use OpenMP. Thus, (1) check out the latest version in the master branch and (2) run `python3 setup.py build_ext --inplace  --openmp` or `python3 setup.py install  --openmp`.

**Comment by wannesm** [comment]
Openmp is now activated by default. It can be deactivated using the global option –noopenmp.

**Comment by andmib** [comment]
Hey @wannesm - thank you for this; I haven't had time to test it out, but I'll build from source and try again later this week.
