### ISSUE TITLE
module' object is not callable

### ISSUE THREAD

**Issue by alligator19** [wannesm/dtaidistance#34]
Dear Friend. 

I have an error. 

```
dist, cost, path = dtw(mfcc1.T, mfcc2.T)
print("The normalized distance between the two : ",dist)   # 0 for similar audios 
```

TypeError: 'module' object is not callable

Can you help .. to resolve?

**Comment by wannesm** [comment]
There is no `dtw` function in the toolbox. You probably mean `dtw.warping_path` or `dtw.distance`. See https://dtaidistance.readthedocs.io/en/latest/usage/dtw.html
