### ISSUE TITLE
Need to install with pip3, otherwise error

### ISSUE THREAD

**Issue by jweissko** [wannesm/dtaidistance#37]
Hi, 

When I tried installing with pip I got the following error: 

line 263, in <module>
        with open('dtaidistance/__init__.py', 'r', encoding='utf-8') as fd:
    TypeError: 'encoding' is an invalid keyword argument for this function

I tried reinstalling with pip3 and it worked. 

Please edit the install doc to "pip3."

Thx.
~Jon

**Comment by wannesm** [comment]
Thanks for noting. It is indeed Python 3 only. I have added this requirement to the setup file such that it gives an error when running pip for Python 2. Calling it 'pip' is the standard also used in the Python documentation. I have added an explicit note in the docs that Python 3 is required though.
