### ISSUE TITLE
basic clustering example fails with error NoneType has no len()

### ISSUE THREAD

**Issue by jweissko** [wannesm/dtaidistance#38]
Resolved. See suggestion for doc clarification below.

Original question:

Hi, 

When I run this clustering example code provided in the docs: 

```
from dtaidistance import dtw
import numpy as np
s1 = np.array([0, 0, 1, 2, 1, 0, 1, 0, 0], dtype=np.double)
s2 = np.array([0.0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0])
s3 = np.array([0.0, 0, 1, 2, 1, 0, 0, 0])
series = [s1, s2, s3]

from dtaidistance import clustering
# Custom Hierarchical clustering
model1 = clustering.Hierarchical(dtw.distance_matrix, {})
# Keep track of full tree by using the HierarchicalTree wrapper class
model2a = clustering.HierarchicalTree(model1)
# You can also pass keyword arguments identical to instantiate a Hierarchical object
model2b = clustering.HierarchicalTree(dists_fun=dtw.distance_matrix, dists_options={})
# SciPy linkage clustering
model3 = clustering.LinkageTree(dtw.distance_matrix, {})
cluster_idx = model3.fit(series)

model2a.plot("hierarchy.png")
```

I get the following error traced back to clustering.py:

```
 line 220, in plot
    self._series_y = [0] * len(self.series)
TypeError: object of type 'NoneType' has no len()
```

I get the same error when I use distance_matrix_fast.

Can you help me?

SOLUTION: 

The above example fit model3, but not model 2b which it seeks to plot. You need to call

`var = model2a.fit(series)`

then you can plot it. 

Updating the doc accordingly would help others avoid this error.

**Comment by wannesm** [comment]
That's correct. We tried to be keep the example compact but that leads to confusion. It is changed in the docs.
