### ISSUE TITLE
compact only keyword for dtw_distance, not dtw_distance_fast

### ISSUE THREAD

**Issue by jweissko** [wannesm/dtaidistance#40]
In the docs on page "Dynamic Time Warping (DTW", in the section entitled "DTW between set of series", after giving an example using dtw.distance_matrix_fast, the doc says: 

"This behaviour can be deactivated by setting the argument compact to true," implying that compact can be set to true in the previous example, which is of distance_matrix_fast.

However, compact is only a keyword in dtw.distance_matrix, and not in the distance_matrix_fast. If you try setting compact to True in distance_matrix_fast, you will get an error. So as not to be misleading, I suggest clarifying this in the doc.

**Comment by wannesm** [comment]
This was an omission. The fix is now added to the master branch in commit a0b99cf33a850cdd4bb9918fd8ea5c1b9d094486.
