### ISSUE TITLE
In clustering, why 'complete' linkage as opposed to other methods?

### ISSUE THREAD

**Issue by jweissko** [wannesm/dtaidistance#41]
Hello,

I noticed that in clustering.py, you use 'complete' linkage rather than single, average or ward. Would you be so kind as to explain why you chose complete linkage? What were the considerations that went into your making this choice? 

~Thank you.

**Comment by wannesm** [comment]
I made it an option for the class.

It depends on the task and application. But for us the reason to use complete linkage is that we prefer clusters in which all series are as similar as possible to each other. In case single linkage is used, one can observe drift in a cluster when finding similar elements. For example, the most similar pair might be based on a series that is close to the boundary. As a result the cluster is more difficult to interpret. See also the figure in the readme for the control chart benchmark.
