### ISSUE TITLE
how can I install the package with Windows environment

### ISSUE THREAD

**Issue by wwd7222117** [wannesm/dtaidistance#43]
thanks

**Comment by wannesm** [comment]
Can you give some more details. It works on our Windows installations with `python setup.py install` or  `pip install dtaidistance`. But Windows is not as well tested as Linux and Mac. Can you add the verbose option `-v` and share the output?

**Comment by wwd7222117** [comment]
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\legend\AppData\Local\Temp\pip-install-nnjtrq7q\dtaidistance\setup.py", line 322, in <module>
        ext_modules=ext_modules
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\__init__.py", line 140, in setup
        return distutils.core.setup(**attrs)
      File "C:\ProgramData\Anaconda3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\ProgramData\Anaconda3\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "C:\ProgramData\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\ProgramData\Anaconda3\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\ProgramData\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\build_ext.py", line 78, in run
        _build_ext.run(self)
      File "C:\ProgramData\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "C:\ProgramData\Anaconda3\lib\distutils\command\build_ext.py", line 339, in run
        self.build_extensions()
      File "C:\Users\legend\AppData\Local\Temp\pip-install-nnjtrq7q\dtaidistance\setup.py", line 178, in build_extensions
        if self.distribution.noopenmp == 0 and not check_openmp(self.compiler.compiler[0]):
    AttributeError: 'MSVCCompiler' object has no attribute 'compiler'
    Compiler type: msvc
    --noopenmp: 0

I have try some methods to solve this problem. But it doesn’t works. I hope you can give some clues to install this package successfully. Thanks !
Sent from Mail for Windows 10

**Comment by Huii** [comment]
I'm on Windows 10 and facing the same issue whenever I attempt to build the package from source. I used to work with an older version without any problems but today I tried to update and ran into this problem.

**Comment by Huii** [comment]
P.S: I managed to install the package by deleting the "and not check_openmp(self.compiler.compiler[0])" part from line 178 of the setup.py file. According to [this link](https://gitlab.gnome.org/GNOME/pygobject/issues/275) "compiler is an attribute on Linux but not Windows". However, I'm not so sure whether this really didn't break anything. Could you please have a look at that? Thank you very much.

**Comment by wannesm** [comment]
Thanks for the detailed feedback. That line is now captured in a try-block to catch differences between the different OS. We have no easy access to various Windows machines to easily check different setups and I don't immediately spot any strange things in the logs. So all feedback is welcome.

**Comment by Huii** [comment]
Your last commit fixed both currently open issues for me. Thank you very much for your work! This package is a very integral part of my daily work and I'm very happy that you are still actively developing it and keep fixing bugs (even if Windows isn't your main target platform). Keep up the good work. :)

**Comment by diamant-x** [comment]
Thanks for the fix, this error seems recurrent in other softwares.
Here is the example of how it is handled in a Gnome-backed software:
https://gitlab.gnome.org/GNOME/pygobject/issues/275
And also highlighted in StackOVerflow:
https://stackoverflow.com/a/56358014

- I tried installing it today from PyPi, but apparently the fix is not pushed there yet. Could you double check that?

Many thanks!

**Comment by wxmgo** [comment]
install fail
AttributeError: 'MSVCCompiler' object has no attribute 'compiler'

**Comment by Huii** [comment]
What's your Windows version 10? Did you pull the latest code from the repo?

**Comment by diamant-x** [comment]
I solved this error on the latest W10 1903 and the pypi version and both the github with the following:
download **Visual Studio Tools _for Build_** from here https://visualstudio.microsoft.com/es/thank-you-downloading-visual-studio/?sku=BuildTools&rel=16
Run the installer in 2 waves:

1.  Install the generic utilities with the bundle of "Development for C++ applications".
2. Rerun the installer and now choose to install the Visual Studio for Community. If asked choose again the "Developmnet for C++ applications".
3. Make sure you open once the visual studio to ensure path and everythig is working (just reach the window to create a new project, and then you cna close".
4. Reboot PC.
5. Try now again to install, it should work.

**Comment by andersonreisoares** [comment]
I manage to solve the issues I had following the steps presented on PyStand install guide (https://pystan.readthedocs.io/en/latest/windows.html#installing-c-compiler).
However, I needed to build it from the source, with pip comand it didn't work.

**Comment by yasirroni** [comment]
Latest install from github clone using `pip install -e .` still return `AttributeError: 'MSVCCompiler' object has no attribute 'compiler' `.

**Comment by wannesm** [comment]
This should indeed not happen. Can you tell which line in setup.py triggers this exception? 
For a few hours 9 days ago, a bug sneaked in the setup.py (version 2.3.3) but that would quite a coincidence.

**Comment by yasirroni** [comment]
Latest from master still got the error.

```
    warning: no files found matching 'examples\hierarchical_clustering.py'                                                                                                  no previously-included directories found matching 'experiments'                                                                                                         no previously-included directories found matching 'venv'                                                                                                                no previously-included directories found matching 'tests\__pycache__'                                                                                                   no previously-included directories found matching 'tests\output'                                                                                                        writing manifest file 'dtaidistance.egg-info\SOURCES.txt'                                                                                                               running build_ext                                                                                                                                                       Traceback (most recent call last):                                                                                                                                        File "<string>", line 1, in <module>                                                                                                                                    File "C:\Data\Git\dtaidistance\setup.py", line 414, in <module>                                                                                                           setup(ext_modules=ext_modules, **setup_kwargs)                                                                                                                        File "C:\Users\muham\AppData\Local\Temp\pip-build-env-r21jtz8c\overlay\Lib\site-packages\setuptools\__init__.py", line 155, in setup                                      return distutils.core.setup(**attrs)                                                                                                                                  File "C:\Users\muham\AppData\Local\Temp\pip-build-env-r21jtz8c\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 148, in setup                               return run_commands(dist)                                                                                                                                             File "C:\Users\muham\AppData\Local\Temp\pip-build-env-r21jtz8c\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands                        dist.run_commands()                                                                                                                                                   File "C:\Users\muham\AppData\Local\Temp\pip-build-env-r21jtz8c\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands                        self.run_command(cmd)                                                                                                                                                 File "C:\Users\muham\AppData\Local\Temp\pip-build-env-r21jtz8c\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command                         cmd_obj.run()                                                                                                                                                         File "C:\Users\muham\AppData\Local\Temp\pip-build-env-r21jtz8c\overlay\Lib\site-packages\setuptools\command\develop.py", line 34, in run                                  self.install_for_development()                                                                                                                                        File "C:\Users\muham\AppData\Local\Temp\pip-build-env-r21jtz8c\overlay\Lib\site-packages\setuptools\command\develop.py", line 114, in install_for_development             self.run_command('build_ext')                                                                                                                                         File "C:\Users\muham\AppData\Local\Temp\pip-build-env-r21jtz8c\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command                          self.distribution.run_command(command)                                                                                                                                File "C:\Users\muham\AppData\Local\Temp\pip-build-env-r21jtz8c\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command                         cmd_obj.run()                                                                                                                                                         File "C:\Users\muham\AppData\Local\Temp\pip-build-env-r21jtz8c\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 79, in run                                _build_ext.run(self)                                                                                                                                                  File "C:\Users\muham\AppData\Local\Temp\pip-build-env-r21jtz8c\overlay\Lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run                             _build_ext.build_ext.run(self)                                                                                                                                        File "C:\Users\muham\AppData\Local\Temp\pip-build-env-r21jtz8c\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 339, in run                    self.build_extensions()                                                                                                                                               File "C:\Data\Git\dtaidistance\setup.py", line 186, in build_extensions                                                                                                   ("gnu-cc" in self.compiler.compiler[0])):                                                                                                                           AttributeError: 'MSVCCompiler' object has no attribute 'compiler'                                                                                                       Compiler type: msvc                                                                                                                                                     --noopenmp: 0                                                                                                                                                           --forceopenmp: 0                                                                                                                                                        --noxpreprocessor: 0                                                                                                                                                    --forcellvm: 0                                                                                                                                                          --forcegnugcc: 0                                                                                                                                                        ----------------------------------------    
```

pip version 21.3.1 
python 3.7
setuptools-git==1.2
