### ISSUE TITLE
The psi parameter not work in dtaidistance.dtw.distance_matrix_fast

### ISSUE THREAD

**Issue by hokitkan** [wannesm/dtaidistance#44]
According to the MODULES document, psi should work on the c base distance matrix module,

`dtaidistance.dtw.distance_matrix_fast(s, max_dist=None, max_length_diff=None, window=None, max_step=None, penalty=None, psi=None, block=None, compact=False, parallel=True, show_progress=False)`

However, I found that the psi parameter do not work on dtaidistance.dtw.distance_matrix_fast module. 

```
s = [np.array([0., 0, 1, 2, 1, 0, 1, 0, 0]),
     np.array([9., 0, 1, 2, 1, 0, 1, 0, 9])]

dtw.distance_matrix(s,compact=True,psi=1)
dtw.distance_matrix_fast(s,compact=True,psi=1)
```

>[0.]
>[12.72792206]

And when I look into the dtw_c.pyx file, I didn't found the psi code included in distance_matrix_nogil function. I am not familiar with c so I maybe read the code wrongly. 

I am using Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit **(AMD64)]** and dtaidistance v1.2.

I really need this features, is there any workaround?
~Thank you.

**Comment by wannesm** [comment]
That was indeed a bug. Thanks for the report. Fixed in commit d30844b9a64c929a1b89f01f4fc6dfa1b8fc789f
