### ISSUE TITLE
The 'parallel' and 'show_progress' parameter didn't work in dtaidistance.dtw.distance_matrix_fast

### ISSUE THREAD

**Issue by hokitkan** [wannesm/dtaidistance#48]
According to the MODULES document, parallel and show_progress should work on the c base distance matrix module,

`dtaidistance.dtw.distance_matrix_fast(s, max_dist=None, max_length_diff=None, window=None, max_step=None, penalty=None, psi=None, block=None, compact=False, parallel=True, show_progress=False)`

However, I found that the both parallel and show_progress parameter do not work in dtaidistance.dtw.distance_matrix_fast module.

```
s = [
    np.array([10., 10, 10, 8, 10, 8, 8, 10, 8]),
    np.array([8., 10, 8, 8, 10, 8]),
    np.array([8., 2, 0, 0, 0, 0, 0, 1, 1]),
    np.array([8., 2, 0, 0, 0, 0, 0, 0, 0]),
    ...
    np.array([9., 0, 1, 2, 1, 0, 1, 0, 9]),
    np.array([0., 0, 0, 8, 10, 8, 8, 10, 8]),
    np.array([1., 2, 0, 0, 0, 0, 0, 1, 1]),
    np.array([1., 2, 0, 0, 0, 0, 0, 1, 3])
    ]

tic = time.clock()
dtw.distance_matrix(s,compact=True,psi=1,show_progress=True,parallel=True)
toc = time.clock()
toc - tic

tic = time.clock()
dtw.distance_matrix_fast(s,compact=True,psi=1,show_progress=True,parallel=True)
toc = time.clock()
toc - tic

tic = time.clock()
dtw.distance_matrix_fast(s,compact=True,psi=1,show_progress=True,parallel=False)
toc = time.clock()
toc - tic
```

>   0%|          | 0/100 [00:00<?, ?it/s]
> 100%|██████████| 100/100 [00:00<00:00, 512.83it/s]
> 900.014613522851514509
> 
> 1.02014512547413254414
>
> 1.00014066557152784057

The progress bar didn't show up in fast module and the parallel parameter seem doesn't function properly as well. I believe there are some bug in the c code.

I am using Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)] and dtaidistance v1.2.

~Thank you.

**Comment by hokitkan** [comment]
For the parallel problem, I solved it by re-installed the package with 
`Compile the C extensions: python3 setup.py build_ext --inplace `
instead of 
`$ python3 setup.py --noopenmp build_ext --inplace `
now my program can run in a parallel manner! 

For the show_progress problem, I think it is some kind of bug just similar with  
https://github.com/wannesm/dtaidistance/issues/44

**Comment by wannesm** [comment]
Thanks for the notification. The parameter `parallel` was indeed fixed in a recent update. The parameter `show_progress` is not supported in the fast version of the implementation as that is written in C. It is only available for the pure Python implementation. The docstrings have been updated to reflect this better.
