### ISSUE TITLE
PrepReadme and MySDistCommand issues in setup.py

### ISSUE THREAD

**Issue by Huii** [wannesm/dtaidistance#52]
I just attempted to install dtaidistance once again on a Windows 10 machine and ran into the issue that the variables "PrepReadme " and "MySDistCommand" could not be found. Thus, I simply removed the following lines (line 282 and line 283) from setup.py:

```
        'readme': PrepReadme,
        'sdist': MySDistCommand,
```

After doing so, I was able to install dtaidistance from source. Could you please have a look at this issue and adjust the file accordingly? Thanks a lot.

**Comment by wannesm** [comment]
This was fixed in commit 9e3f3f0 .
