### ISSUE TITLE
Why DTW distance are so different when using or not use_c flag

### ISSUE THREAD

**Issue by dariopascu** [wannesm/dtaidistance#53]
According to the documentation, when this flag is set to `True` only means that distance function use precompiled functions in C.
But when I check both values they are so different as we can check in the image bellow.

![image](https://user-images.githubusercontent.com/25616480/62720944-64cbdf80-ba0b-11e9-92dd-197f7d256bad.png)

I assume that this is a wrong behavior, I´m wrong?
Could you tell me, if I'm wrong, what makes this difference?

Thanks in advance!

**Comment by wannesm** [comment]
This is indeed not intended behaviour. Can you also share how the signals datastructure looks like or is generated such that I can make it a unit test?

**Comment by dariopascu** [comment]
Every signal is a randomly generated (with some conditions) and the datastructure is formed by an array of arrays. You can see it more detailed in the following image.

![imagen](https://user-images.githubusercontent.com/25616480/70627444-842b8100-1c26-11ea-92e8-a3b9fde75b2a.png)
Here we have the singnal structure and a specific signal plot.

Hope this help you, thanks a lot!

**Comment by wannesm** [comment]
The numbers are too large. The cumulative difference grows too large to be supported on a 32 bit representation and overflows. That's probably the explanation. Unfortunately there is not yet a check built-in.

**Comment by wannesm** [comment]
I think this is solved in #50 .
