### ISSUE TITLE
will it work for  multivariate  time series classification for example mixture of categorical and continues data? 

### ISSUE THREAD

**Issue by Sandy4321** [wannesm/dtaidistance#54]
will it work for  multivariate  time series classification for example mixture of categorical and continues data? 
	for example at time t1 we have observation: red, 2.4 , 5, 12.456 and time t2: green, 3.5, 2, 45.78; time t3: black, 5.6, 7, 23.56; t4: red, 2.1, 5, 12.6 ?

**Comment by Huii** [comment]
No, I don't think that this would work. You can, however, transform the colours to integers or floats first but I doubt that this would produce any meaningful results as DTW compares signals with each other. In most cases, those signals stem from some sensor(s).

**Comment by wannesm** [comment]
Correct, the toolbox does not support categorical variables.  Making it numbers works but it might be a mismatch with the meaning of the categorical variables. 

It is, however, not difficult to change the function. We didn’t here for performance reasons. You can change the (x[i]-y[i])^2 in the inner loop by a function that returns the distance between two categorical symbols instead of the difference between two numbers.

**Comment by Sandy4321** [comment]
I see, thanks for answer, let me know if/when you add this option to your code

**Comment by wannesm** [comment]
The `dp` method in the `dp` package already supports this functionality (it's slower but more generic such that you can pass a custom function). It is also used to implement Needleman-Wunsch. See that function for an example: https://github.com/wannesm/dtaidistance/blob/45cc77ac3b98e21988692473c11f29e456e72789/dtaidistance/alignment.py#L20

**Comment by Sandy4321** [comment]
Super thanks for reference
https://github.com/wannesm/dtaidistance/blob/45cc77ac3b98e21988692473c11f29e456e72789/dtaidistance/alignment.py#L20

But this one is not for multivariate time series
Or it can be useful for multivariate case as well?

**Comment by wannesm** [comment]
The `dp` method takes a function for the distance between to points as an argument. Support for multivariate depends on the implementation of that function. The Needleman Wunsch function is just an example (which is univariate).
