### ISSUE TITLE
How exactly is the distance added by a penalty calculated?

### ISSUE THREAD

**Issue by dnonatar** [wannesm/dtaidistance#56]
For example, if I started with

`from dtaidistance import dtw`
`s1 = [1,2,3,4,1,2,3]`  
`s2 = [2,3,4,1,2,3,4]`
`distance, paths = dtw.warping_paths(s1, s2,penalty=0)`

The resulting distance was 1.4142135623730951.

 When I set penalty = 10, the distance would be 3.872983346207417.

How did the distance go from 1.4142135623730951 to 3.872983346207417?
 A paper or any other references would be very helpful.

Thanks!

**Comment by wannesm** [comment]
The penalty will make the algorithm to choose not to do a shift and, in this case, avoid the penalty. The resulting distance is the sqrt(1+1+1+3^2+1+1+1) = 3.37...

Fyi, with the penalty and the shift the distance would be 3.46..., which is higher and thus not the best path.

**Comment by DanBenHa** [comment]
Related to this: Is the penalty the same for all magnitudes of warping? For example, is a shift of 10 steps penalised with the same penalty as a 1 step shift? Or is it somehow scaled?

**Comment by wannesm** [comment]
It is a constant value added for each step that is an expansion or deletion:

```
dtw[i, j] = (s1[i]-s2[j])**2 + min(
                    dtw[i-1, j  ] + penalty,  // vertical   / insertion / expansion
                    dtw[i  , j-1] + penalty,  // horizontal / deletion  / compression
                    dtw[i-1, j-1])            // diagonal   / match
```
