### ISSUE TITLE
ValueError: negative dimensions are not allowed

### ISSUE THREAD

**Issue by ghost** [wannesm/dtaidistance#62]
We are getting a weird error using this library that I cannot debug. I have tried to set the logging level to debug and seeing what I can find, but no luck. 

```
INFO:be.kuleuven.dtai.distance:Computing distances
INFO:be.kuleuven.dtai.distance:Compute distances in pure C (parallel=True)
Traceback (most recent call last):
  File "rt/clustering/rt_cluster_trainer.py", line 250, in <module>
    clustering.run()
  File "rt/clustering/rt_cluster_trainer.py", line 183, in run
    model = cluster_library.train()
  File "/opt/grok/grok3/domain/clustering/hierarchical_clustering.py", line 241, in train
    models = self.perform_clustering(self.buckets, self.kvalues, self.linkage_method)
  File "/opt/grok/grok3/domain/clustering/hierarchical_clustering.py", line 208, in perform_clustering
    y = self.calculate_distance_matrix()
  File "/opt/grok/grok3/domain/clustering/hierarchical_clustering.py", line 199, in calculate_distance_matrix
    y = dtw.distance_matrix_fast(self.frequency_counts, window=self.dtw_radius, compact=True)
  File "/opt/grok/ve3/lib/python3.7/site-packages/dtaidistance/dtw.py", line 548, in distance_matrix_fast
    use_c=True, use_nogil=True, show_progress=False)
  File "/opt/grok/ve3/lib/python3.7/site-packages/dtaidistance/dtw.py", line 416, in distance_matrix
    dists = dtw_c.distance_matrix_nogil(s, is_parallel=parallel, **dist_opts)
  File "dtaidistance/dtw_c.pyx", line 586, in dtaidistance.dtw_c.distance_matrix_nogil
  File "dtaidistance/dtw_c.pyx", line 657, in dtaidistance.dtw_c.distance_matrix_nogil_c_p
ValueError: negative dimensions are not allowed

```

We are using the library exactly like the documentation

```
from dtaidistance import dtw
import numpy as np
series = [
    np.array([0, 0, 1, 2, 1, 0, 1, 0, 0], dtype=np.double),
    np.array([0.0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0]),
    np.array([0.0, 0, 1, 2, 1, 0, 0, 0])]
ds = dtw.distance_matrix_fast(series)
```

Our distance matrix is huge, so I cannot post it here, but I have written some code that tests each timeseries fed into the algorithm and they are all the same shape `(307,)`, there are no negative values, there are no NaN.

Can someone shed some light on what this error actually means? There is nothing wrong with our data as far as we know...If we take random samples of the data, say only 50% of it, excluding many timeseries, it seems to work fine. Is there a single timeseries numpy array breaking it?

**Comment by wannesm** [comment]
Can you provide the arguments, except the time series `s` argument, you pass to the `dtw.distance_matrix_fast` function? And for the time series `s` its type and size and also for its elements if you use a list?

**Comment by Adarah** [comment]
I'm receiving the same error. My code is `dists = dtw.distance_matrix_fast(padded, window=int(0.01 * window * padded.shape[1]))` where padded is an array of arrays, with shape (62706, 104). Here's a sample of the array

```
array([[ 0.,  0.,  0.,  0.,  2.,  4.,  5., 10., 11., 10., 10.,  6.,  3.,
         2.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  0.,  2.,
         4.,  4.,  5.,  5.,  3.,  4.,  4.,  2.,  2.,  2.,  3.,  3.,  4.,
         4.,  4.,  4.,  2.,  2.,  3.,  3.,  7.,  6.,  4.,  4.,  8.,  8.,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [ 1., nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [ 3.,  4., 11., 13., 12., 10.,  3.,  1.,  5.,  3., 14., 20., 37.,
        40., 38., 31., 18., 10.,  9., 12.,  8., 16., 15., 19., 27., 26.,
        30., 23., 18., 15., 13., 25., 28., 25., 27., 15.,  8., 11., 13.,
        23., 18., 12.,  6., nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]])
```
The code works fine if i use a limited part of the array (say, the first 1k lines), but once i input everything i get the negative dimensions error. @wannesm

**Comment by wannesm** [comment]
Thanks for the detailed feedback.

For size 62706, the code had an int32 overflow error. This is fixed now. If the required size for the datastructures is too large to be represented, the code now prints an error message.

The max size is based on the definition of Py_ssize_t in Cython. Also on 64 bit systems this can be a 32 bit type. I'm unsure when what is chosen by Cython. More insights are welcome.

in any case, it is recommended to compute the distances in blocks instead of all together, even for serial computation. The code is not (yet) optimized for large distance matrices in one go because we had a parallel approach in mind.

**Comment by wannesm** [comment]
FYI, version 2 of the library now supports 64bit address space and can thus handle larger Numpy arrays. The beta version is available from: https://github.com/wannesm/dtaidistance/tree/v2
