### ISSUE TITLE
Is there any C-implementation for ndim DTW?

### ISSUE THREAD

**Issue by harashm** [wannesm/dtaidistance#63]
Hi,
First, thanks for the great repo!

Maybe I missed, but there is any C-implementation for DTW in the n-dimensional case?

I found 'dtw_ndim.py' which handles ndim case, but 'dtw_c' (at line 22) are not used at all in this file.

(For the 1-dim case, I can see the C-implementation)

Thanks!

**Comment by wannesm** [comment]
There is no C version for ndim in the current version.

**Comment by wannesm** [comment]
FYI, in version 2 this is now supported (including parallelization). Beta is available from:
https://github.com/wannesm/dtaidistance/tree/v2
