### ISSUE TITLE
Warping path between two sequences

### ISSUE THREAD

**Issue by xman236** [wannesm/dtaidistance#67]
Hi all,

Assuming two sequences **a,b** are given. **a** has the role of the reference sequence.
Is there a way to compute warping path between two sequences? More precisely, a way to align the sequence **b** with **a** and return the aligned sequence **b_aligned** ?

**Comment by xman236** [comment]
Oh, the function `warp(from_s, to_s, **kwargs)` exaclty does the job described above.
However, the result shows an incorrect normalization. 

With DTW aligned ( reference sequence is the orange one):
![image](https://user-images.githubusercontent.com/42341018/75437477-87492a00-5956-11ea-98f5-9499b2cbe646.png)

Original shapes:
![image](https://user-images.githubusercontent.com/42341018/75437029-e22e5180-5955-11ea-8a84-99aa69c2b82e.png)

**Comment by wannesm** [comment]
What do you mean exactly with 'incorrect normalization'? Multiple definitions are possible. The toolbox uses a simple averaging strategy.
