### ISSUE TITLE
TypeError: 'int' object is not iterable (Hierarchical clustering)

### ISSUE THREAD

**Issue by nikita-mishunyayev** [wannesm/dtaidistance#74]
Need to fix this line https://github.com/wannesm/dtaidistance/blob/master/dtaidistance/clustering.py#L126
to:
`cluster_idx[i] = set(list(i))` or `cluster_idx[i] = set([i])`

because `max_dist` parameter is not working:
```
TypeError                                 Traceback (most recent call last)
<ipython-input-23-6e56fc137dd1> in <module>
      1 dtw_model = Hierarchical(dtw.distance_matrix_fast, {}, max_dist=500)
----> 2 clusters = dtw_model.fit(piece_series)
      3 
      4 # Keep track of full tree by using the HierarchicalTree wrapper class

/opt/conda/lib/python3.7/site-packages/dtaidistance/clustering.py in fit(self, series)
    124                 prototypes.append(i)
    125                 if i not in cluster_idx:
--> 126                     cluster_idx[i] = set(i)
    127         return cluster_idx
    128 

TypeError: 'int' object is not iterable
```

**Full code:**
1. Working example:
```
dtw_model = Hierarchical(dtw.distance_matrix_fast, {})
clusters = dtw_model.fit(piece_series)

# Keep track of full tree by using the HierarchicalTree wrapper class
dtw_model_tree = HierarchicalTree(dtw_model)
_ = dtw_model_tree.fit(piece_series)
```
2. Not working example:
```
dtw_model = Hierarchical(dtw.distance_matrix_fast, {}, max_dist=500)
clusters = dtw_model.fit(piece_series)

# Keep track of full tree by using the HierarchicalTree wrapper class
dtw_model_tree = HierarchicalTree(dtw_model)
_ = dtw_model_tree.fit(piece_series)
```

**Comment by wannesm** [comment]
Thanks, it's fixed.

**Comment by Skwal77** [comment]
Hey, guys,
I have exactly the same problem and the two options @nikita-mishunyayev  offer does not solve my case.

**Comment by Skwal77** [comment]
What shoud i do?

**Comment by nikita-mishunyayev** [comment]
Show your input data pls

**Comment by Skwal77** [comment]
![data](https://user-images.githubusercontent.com/68301613/87473419-67599080-c5ef-11ea-877d-779b0a1f530a.JPG)

**Comment by Skwal77** [comment]
That's my series (1205*1205)
@nikita-mishunyayev

**Comment by Skwal77** [comment]
Sorry it's the result of "ds = dtw.distance_matrix_fast(Serie)" @nikita-mishunyayev

**Comment by nikita-mishunyayev** [comment]
Do all your series have different length?

**Comment by Skwal77** [comment]
no they have the same size

**Comment by Skwal77** [comment]
[dataDTW.txt](https://github.com/wannesm/dtaidistance/files/4921338/dataDTW.txt)

**Comment by Skwal77** [comment]
remove txt for csv and you will get the data i use for my example

**Comment by Skwal77** [comment]
[dataSerieDTW.txt](https://github.com/wannesm/dtaidistance/files/4921414/dataSerieDTW.txt)

**Comment by Skwal77** [comment]
This is my serie @nikita-mishunyayev

**Comment by Skwal77** [comment]
@wannesm  let me know if you have a solution for this problem

**Comment by wannesm** [comment]
I cannot replicate the error with your files. Make sure to use the latest version. I will soon also switch the main branch to the v2 version. You can already start using that version by using 

```
pip install --upgrade --force-reinstall git+https://github.com/wannesm/dtaidistance@v2
```
