### ISSUE TITLE
Visualization of path for the distance_matrix

### ISSUE THREAD

**Issue by samoalfred** [wannesm/dtaidistance#77]
I have a matrix of sequences. I want to visualize the warping paths as it is done for two sequences. Is that possible? If it is, how is it done?

**Comment by wannesm** [comment]
That would be more than two dimensions, I don't know any methods that support this. You can of course plot all pairwise warping paths.

**Comment by samoalfred** [comment]
Alright thanks. But I have close to 200 trajectories which I have put in a matrix. So I was hoping to get a mean trajectory using this technique and then plot it to visualize it.

**Comment by wannesm** [comment]
In that case I'd cluster the trajectories and plot a representative of each cluster or use the barycenters techniek. The tslearn library has a nice implementation: https://tslearn.readthedocs.io/en/stable/gen_modules/tslearn.barycenters.html

**Comment by samoalfred** [comment]
Okay thanks. I will try it out.
