### ISSUE TITLE
DOC: dtaidistance.dtw.warping_paths_fast

### ISSUE THREAD

**Issue by keithbriggs** [wannesm/dtaidistance#79]
dtaidistance.dtw.warping_paths_fast(s1, s2, window=None, max_dist=None, max_step=None, max_length_diff=None, penalty=None, psi=None)
        Fast C version of distance().

Why isn't it a fast C version of warping_paths?

**Comment by wannesm** [comment]
That's a copy-paste error, thanks for noticing. It does call a C implementation of the warping_paths method.
