### ISSUE TITLE
Cannot install dtaidistance on windows 10 

### ISSUE THREAD

**Issue by vranjan** [wannesm/dtaidistance#83]
(base) PS C:\> pip install C:\Users\vranjan2\Desktop\dtaidistance-1.2.3.tar.gz
Processing c:\users\vranjan2\desktop\dtaidistance-1.2.3.tar.gz
Requirement already satisfied: numpy in c:\users\vranjan2\anaconda3\envs\mynlp\lib\site-packages (from dtaidistance==1.2.3) (1.18.1)
Requirement already satisfied: cython in c:\users\vranjan2\anaconda3\envs\mynlp\lib\site-packages (from dtaidistance==1.2.3) (0.29.15)
Building wheels for collected packages: dtaidistance
  Building wheel for dtaidistance (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\vranjan2\Anaconda3\envs\mynlp\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\vranjan2\\AppData\\Local\\Temp\\pip-req-build-n43qqmv2\\setup.py'"'"'; __file__='"'"'C:\\Users\\vranjan2\\AppData\\Local\\Temp\\pip-req-build-n43qqmv2\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\vranjan2\AppData\Local\Temp\pip-wheel-irn6opxz'
       cwd: C:\Users\vranjan2\AppData\Local\Temp\pip-req-build-n43qqmv2\
  Complete output (38 lines):
  running bdist_wheel
  Using the following environment variables:
  CC=
  CPPFLAGS=
  CFLAGS=
  LDFLAGS=
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\dtaidistance
  copying dtaidistance\alignment.py -> build\lib.win-amd64-3.7\dtaidistance
  copying dtaidistance\clustering.py -> build\lib.win-amd64-3.7\dtaidistance
  copying dtaidistance\dp.py -> build\lib.win-amd64-3.7\dtaidistance
  copying dtaidistance\dtw.py -> build\lib.win-amd64-3.7\dtaidistance
  copying dtaidistance\dtw_ndim.py -> build\lib.win-amd64-3.7\dtaidistance
  copying dtaidistance\dtw_ndim_visualisation.py -> build\lib.win-amd64-3.7\dtaidistance
  copying dtaidistance\dtw_visualisation.py -> build\lib.win-amd64-3.7\dtaidistance
  copying dtaidistance\dtw_weighted.py -> build\lib.win-amd64-3.7\dtaidistance
  copying dtaidistance\util.py -> build\lib.win-amd64-3.7\dtaidistance
  copying dtaidistance\__init__.py -> build\lib.win-amd64-3.7\dtaidistance
  running egg_info
  writing dtaidistance.egg-info\PKG-INFO
  writing dependency_links to dtaidistance.egg-info\dependency_links.txt
  writing requirements to dtaidistance.egg-info\requires.txt
  writing top-level names to dtaidistance.egg-info\top_level.txt
  reading manifest file 'dtaidistance.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'dtaidistance.egg-info\SOURCES.txt'
  copying dtaidistance\dtw_c.c -> build\lib.win-amd64-3.7\dtaidistance
  copying dtaidistance\dtw_c.pyx -> build\lib.win-amd64-3.7\dtaidistance
  running build_ext
  Compiler type: msvc
  --noopenmp: 0
  WARNING: Cannot check for OpenMP, assuming to be available
  'MSVCCompiler' object has no attribute 'compiler'
  building 'dtaidistance.dtw_c' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for dtaidistance
  Running setup.py clean for dtaidistance
Failed to build dtaidistance
Installing collected packages: dtaidistance
    Running setup.py install for dtaidistance ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\vranjan2\Anaconda3\envs\mynlp\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\vranjan2\\AppData\\Local\\Temp\\pip-req-build-n43qqmv2\\setup.py'"'"'; __file__='"'"'C:\\Users\\vranjan2\\AppData\\Local\\Temp\\pip-req-build-n43qqmv2\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\vranjan2\AppData\Local\Temp\pip-record-8a7dhj4p\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\vranjan2\Anaconda3\envs\mynlp\Include\dtaidistance'
         cwd: C:\Users\vranjan2\AppData\Local\Temp\pip-req-build-n43qqmv2\
    Complete output (38 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\dtaidistance
    copying dtaidistance\alignment.py -> build\lib.win-amd64-3.7\dtaidistance
    copying dtaidistance\clustering.py -> build\lib.win-amd64-3.7\dtaidistance
    copying dtaidistance\dp.py -> build\lib.win-amd64-3.7\dtaidistance
    copying dtaidistance\dtw.py -> build\lib.win-amd64-3.7\dtaidistance
    copying dtaidistance\dtw_ndim.py -> build\lib.win-amd64-3.7\dtaidistance
    copying dtaidistance\dtw_ndim_visualisation.py -> build\lib.win-amd64-3.7\dtaidistance
    copying dtaidistance\dtw_visualisation.py -> build\lib.win-amd64-3.7\dtaidistance
    copying dtaidistance\dtw_weighted.py -> build\lib.win-amd64-3.7\dtaidistance
    copying dtaidistance\util.py -> build\lib.win-amd64-3.7\dtaidistance
    copying dtaidistance\__init__.py -> build\lib.win-amd64-3.7\dtaidistance
    running egg_info
    writing dtaidistance.egg-info\PKG-INFO
    writing dependency_links to dtaidistance.egg-info\dependency_links.txt
    writing requirements to dtaidistance.egg-info\requires.txt
    writing top-level names to dtaidistance.egg-info\top_level.txt
    Using the following environment variables:
    CC=
    CPPFLAGS=
    CFLAGS=
    LDFLAGS=
    reading manifest file 'dtaidistance.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'dtaidistance.egg-info\SOURCES.txt'
    copying dtaidistance\dtw_c.c -> build\lib.win-amd64-3.7\dtaidistance
    copying dtaidistance\dtw_c.pyx -> build\lib.win-amd64-3.7\dtaidistance
    running build_ext
    Compiler type: msvc
    --noopenmp: 0
    WARNING: Cannot check for OpenMP, assuming to be available
    'MSVCCompiler' object has no attribute 'compiler'
    building 'dtaidistance.dtw_c' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\vranjan2\Anaconda3\envs\mynlp\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\vranjan2\\AppData\\Local\\Temp\\pip-req-build-n43qqmv2\\setup.py'"'"'; __file__='"'"'C:\\Users\\vranjan2\\AppData\\Local\\Temp\\pip-req-build-n43qqmv2\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\vranjan2\AppData\Local\Temp\pip-record-8a7dhj4p\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\vranjan2\Anaconda3\envs\mynlp\Include\dtaidistance' Check the logs for full command output.

**Comment by vranjan** [comment]
Following this thread: https://answers.microsoft.com/en-us/windows/forum/all/microsoft-visual-c-140/6f0726e2-6c32-4719-9fe5-aa68b5ad8e6d
I did download 
Microsoft C++ Build Tools
Standalone MSVC compiler, libraries, and scripts
from https://visualstudio.microsoft.com/visual-cpp-build-tools/ and installed it... 

And also tried 
pip install dtaidistance

and I still get the errors reported above.

**Comment by wannesm** [comment]
A new version is released that should compile on Windows 10 using MSVC.

The error seems to indicate a problem with your local installation, though.
