### ISSUE TITLE
Installation of package is looking for #include "lib/DTAIDistanceC/DTAIDistanceC/globals.h

### ISSUE THREAD

**Issue by data-distance** [wannesm/dtaidistance#85]
I'm trying to install the package from github in a new conda environment. Please advise, I sincerely appreciate your time. This is the error message I'm getting:

(testing_dtaidistance) [PROJECT_DATA\USER@a-vf3qq94fs8vh dtaidistance]$ python3 setup.py build_ext --inplace
running build_ext
Using the following environment variables:
CC=/home/USER/anaconda3/envs/testing_dtaidistance/bin/x86_64-conda_cos6-linux-gnu-cc
CPPFLAGS=-Idtaidistance/lib/DTAIDistanceC/DTAIDistanceC -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/USER/anaconda3/envs/testing_dtaidistance/include
CFLAGS=
LDFLAGS=-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/home/USER/anaconda3/envs/testing_dtaidistance/lib -Wl,-rpath-link,/home/USER/anaconda3/envs/testing_dtaidistance/lib -L/home/USER/anaconda3/envs/testing_dtaidistance/lib
Compiler type: unix
--noopenmp: 0
Checking for OpenMP availability
/home/USER/anaconda3/envs/testing_dtaidistance/bin/x86_64-conda_cos6-linux-gnu-cc -dM -E -fopenmp -stdout=-1 input= encoding=ascii
... found OpenMP
All extensions:
[<setuptools.extension.Extension('dtaidistance.dtw_cc') at 0x7fe8bca0fa90>, <setuptools.extension.Extension('dtaidistance.ed_cc') at 0x7fe8bc96e650>, <setuptools.extension.Extension('dtaidistance.dtw_cc_omp') at 0x7fe8bc96ee50>, <setuptools.extension.Extension('dtaidistance.dtw_cc_numpy') at 0x7fe8bc9d3490>]
building 'dtaidistance.dtw_cc' extension
/home/USER/anaconda3/envs/testing_dtaidistance/bin/x86_64-conda_cos6-linux-gnu-cc -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/USER/anaconda3/envs/testing_dtaidistance/include -Idtaidistance/lib/DTAIDistanceC/DTAIDistanceC -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/USER/anaconda3/envs/testing_dtaidistance/include -fPIC -I./dtaidistance -I/home/USER/anaconda3/envs/testing_dtaidistance/include/python3.7m -c dtaidistance/dtw_cc.c -o build/temp.linux-x86_64-3.7/dtaidistance/dtw_cc.o -Xpreprocessor -fopenmp
dtaidistance/dtw_cc.c:628:10: fatal error: lib/DTAIDistanceC/DTAIDistanceC/globals.h: No such file or directory
 #include "lib/DTAIDistanceC/DTAIDistanceC/globals.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
error: command '/home/USER/anaconda3/envs/testing_dtaidistance/bin/x86_64-conda_cos6-linux-gnu-cc' failed with exit status 1

**Comment by data-distance** [comment]
If it helps, the following is a summary of this conda environment and a list of packages installed here for reproducibility:

(testing_dtaidistance) [PROJECT_DATA\USER@a-vf3qq94fs8vh dtaidistance]$ conda info
active environment : testing_dtaidistance
active env location : /home/USER/anaconda3/envs/testing_dtaidistance
shell level : 1
user config file : /home/USER/.condarc
populated config files : /home/USER/.condarc
conda version : 4.8.4
conda-build version : 3.18.11
python version : 3.8.3.final.0
virtual packages : __glibc=2.26
base environment : /home/USER/anaconda3  (writable)
channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
package cache : /home/USER/anaconda3/pkgs
                          /home/USER/.conda/pkgs
envs directories : /home/USER/anaconda3/envs
                          /home/USER/.conda/envs
platform : linux-64
netrc file : None
offline mode : False

# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
_r-mutex                  1.0.1               anacondar_1    conda-forge
binutils_impl_linux-64    2.34                 h53a641e_7    conda-forge
binutils_linux-64         2.34                hc952b39_20    conda-forge
bwidget                   1.9.14                        0    conda-forge
bzip2                     1.0.8                h516909a_2    conda-forge
c-ares                    1.16.1               h516909a_0    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
cairo                     1.16.0            h3fc0475_1005    conda-forge
certifi                   2020.6.20        py37hc8dfbb8_0    conda-forge
cffi                      1.14.1           py37h2b28604_0    conda-forge
curl                      7.71.1               he644dc0_4    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cython                    0.29.21          py37h3340039_0    conda-forge
fontconfig                2.13.1            h1056068_1002    conda-forge
freetype                  2.10.2               he06d7ca_0    conda-forge
fribidi                   1.0.10               h516909a_0    conda-forge
gcc_impl_linux-64         7.5.0                hd420e75_6    conda-forge
gcc_linux-64              7.5.0               h09487f9_20    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
gfortran_impl_linux-64    7.5.0                hdf63c60_6    conda-forge
gfortran_linux-64         7.5.0               h09487f9_20    conda-forge
glib                      2.65.0               h6f030ca_0    conda-forge
graphite2                 1.3.13            he1b5a44_1001    conda-forge
gsl                       2.6                  h294904e_0    conda-forge
gxx_impl_linux-64         7.5.0                hdf63c60_6    conda-forge
gxx_linux-64              7.5.0               h09487f9_20    conda-forge
harfbuzz                  2.7.0                hee91db6_0    conda-forge
icu                       67.1                 he1b5a44_0    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
jpeg                      9d                   h516909a_0    conda-forge
kiwisolver                1.2.0            py37h99015e2_0    conda-forge
krb5                      1.17.1               hfafb76e_2    conda-forge
lcms2                     2.11                 hbd6801e_0    conda-forge
ld_impl_linux-64          2.34                 h53a641e_7    conda-forge
libblas                   3.8.0               17_openblas    conda-forge
libcblas                  3.8.0               17_openblas    conda-forge
libcurl                   7.71.1               hcdd3856_4    conda-forge
libedit                   3.1.20191231         h46ee950_1    conda-forge
libev                     4.33                 h516909a_0    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.3.0               h24d8f2e_14    conda-forge
libgfortran-ng            7.5.0               hdf63c60_14    conda-forge
libgomp                   9.3.0               h24d8f2e_14    conda-forge
libiconv                  1.15              h516909a_1006    conda-forge
liblapack                 3.8.0               17_openblas    conda-forge
libnghttp2                1.41.0               hab1572f_1    conda-forge
libopenblas               0.3.10          pthreads_hb3c22a3_4    conda-forge
libpng                    1.6.37               hed695b0_2    conda-forge
libssh2                   1.9.0                hab1572f_5    conda-forge
libstdcxx-ng              9.3.0               hdf63c60_14    conda-forge
libtiff                   4.1.0                hc7e4089_6    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libwebp-base              1.1.0                h516909a_3    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.10               h72b56ed_2    conda-forge
lz4-c                     1.9.2                he1b5a44_1    conda-forge
make                      4.3                  h516909a_0    conda-forge
markupsafe                1.1.1            py37h8f50634_1    conda-forge
matplotlib                3.3.1                         0    conda-forge
matplotlib-base           3.3.1            py37hd478181_0    conda-forge
ncurses                   6.2                  he1b5a44_1    conda-forge
numpy                     1.19.1           py37h8960a57_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openssl                   1.1.1g               h516909a_1    conda-forge
pango                     1.42.4               h7062337_4    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
pillow                    7.2.0            py37h718be6c_1    conda-forge
pip                       20.2.2                     py_0    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
python                    3.7.8           h6f2ec95_1_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
r                         3.6                    r36_1004    conda-forge
r-base                    3.6.3                he766273_3    conda-forge
r-boot                    1.3_25            r36h6115d3f_1    conda-forge
r-class                   7.3_17            r36hcdcec82_1    conda-forge
r-cluster                 2.1.0             r36h9bbef5b_3    conda-forge
r-codetools               0.2_16          r36h6115d3f_1002    conda-forge
r-foreign                 0.8_76            r36hcdcec82_1    conda-forge
r-kernsmooth              2.23_17           r36hfa343cc_1    conda-forge
r-lattice                 0.20_41           r36hcdcec82_2    conda-forge
r-mass                    7.3_51.6          r36hcdcec82_2    conda-forge
r-matrix                  1.2_18            r36h7fa42b6_3    conda-forge
r-mgcv                    1.8_31            r36h7fa42b6_1    conda-forge
r-nlme                    3.1_148           r36h9bbef5b_0    conda-forge
r-nnet                    7.3_14            r36hcdcec82_1    conda-forge
r-recommended             3.6                    r36_1004    conda-forge
r-rpart                   4.1_15            r36hcdcec82_2    conda-forge
r-spatial                 7.3_12            r36hcdcec82_1    conda-forge
r-survival                3.2_3             r36hcdcec82_0    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
rpy2                      3.3.2           py37r36h03ebfcd_0    conda-forge
sed                       4.8                  hbfbb72e_0    conda-forge
setuptools                49.6.0           py37hc8dfbb8_0    conda-forge
simplegeneric             0.8.1                      py_1    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.32.3               h4cf870e_1    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
tktable                   2.10                 h555a92e_3    conda-forge
tornado                   6.0.4            py37h8f50634_1    conda-forge
tqdm                      4.48.2             pyh9f0ad1d_0    conda-forge
tzlocal                   2.1                pyh9f0ad1d_0    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.11               h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h516909a_1007    conda-forge
zstd                      1.4.5                h6597ccf_2    conda-forge

Environment created by:
conda create --name testing_dtaidistance python=3.7 R=3.6
conda install -n testing_dtaidistance rpy2 cython numpy matplotlib tqdm

**Comment by wannesm** [comment]
I fixed the c-files in the git repository. The installation now works on linux  (tested on Ubuntu 18.04.5 LTS).
