### ISSUE TITLE
Installation issue: error: ‘PTRDIFF_MAX’ undeclared

### ISSUE THREAD

**Issue by xiaoluffy** [wannesm/dtaidistance#86]
I'm trying to install the package by using 'pip install dtaidistance[numpy]'. I'd appreciate it if you could help me out
. This is the error message I'm getting:

    gcc -pthread -B /opt/anaconda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I./dtaidistance -I/opt/anaconda/include/python3.7m -c dtaidistance/dtw_cc.c -o build/temp.linux-x86_64-3.7/dtaidistance/dtw_cc.o -Xpreprocessor -fopenmp -Idtaidistance/lib/DTAIDistanceC/DTAIDistanceC
    In file included from dtaidistance/dtw_cc.c:618:0:
    dtaidistance/lib/DTAIDistanceC/DTAIDistanceC/dtw.h:32:12: warning: ‘printPrecision’ defined but not used [-Wunused-variable]
     static int printPrecision = 3;
                ^~~~~~~~~~~~~~
    gcc -pthread -B /opt/anaconda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I./dtaidistance -I/opt/anaconda/include/python3.7m -c dtaidistance/lib/DTAIDistanceC/DTAIDistanceC/dtw.c -o build/temp.linux-x86_64-3.7/dtaidistance/lib/DTAIDistanceC/DTAIDistanceC/dtw.o -Xpreprocessor -fopenmp -Idtaidistance/lib/DTAIDistanceC/DTAIDistanceC
    dtaidistance/lib/DTAIDistanceC/DTAIDistanceC/dtw.c: In function ‘dtw_distances_length’:
    dtaidistance/lib/DTAIDistanceC/DTAIDistanceC/dtw.c:1070:21: error: ‘PTRDIFF_MAX’ undeclared (first use in this function); did you mean ‘__PTRDIFF_MAX__’?
             max_value = PTRDIFF_MAX;
                         ^~~~~~~~~~~
                         __PTRDIFF_MAX__
    dtaidistance/lib/DTAIDistanceC/DTAIDistanceC/dtw.c:1070:21: note: each undeclared identifier is reported only once for each function it appears in
    dtaidistance/lib/DTAIDistanceC/DTAIDistanceC/dtw.c:1072:21: error: ‘SIZE_MAX’ undeclared (first use in this function); did you mean ‘SIGRTMAX’?
             max_value = SIZE_MAX;
                         ^~~~~~~~
                         SIGRTMAX
    error: command 'gcc' failed with exit status 1

More details:
# conda info

     active environment : base
    active env location : /opt/anaconda
            shell level : 1
       user config file : /root/.condarc
 populated config files : /root/.condarc
          conda version : 4.8.3
    conda-build version : 3.17.8
         python version : 3.7.3.final.0
       virtual packages : __glibc=2.27
       base environment : /opt/anaconda  (writable)
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud//pytorch/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud//pytorch/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/anaconda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/anaconda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.21.0 CPython/3.7.3 Linux/4.15.0-88-generic ubuntu/18.04.4 glibc/2.27
                UID:GID : 0:0
             netrc file : None
           offline mode : False

# apt show libomp-dev
Package: libomp-dev
Version: 5.0.1-1
Priority: extra
Section: universe/libdevel
Source: openmprtl
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: LLVM Packaging Team <pkg-llvm-team@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 29.7 kB
Depends: libomp5 (= 5.0.1-1)
Suggests: libomp-doc
Breaks: libiomp-dev (<< 3.7-1)
Replaces: libiomp-dev (<< 3.7-1)
Homepage: http://openmp.llvm.org/
Supported: 3y
Download-Size: 5,088 B
APT-Manual-Installed: yes
APT-Sources: http://mirrors.tencentyun.com/ubuntu bionic/universe amd64 Packages
Description: LLVM OpenMP runtime - dev package
 The runtime is the part of the OpenMP implementation that your code is
 linked against, and that manages the multiple threads in an OpenMP program
 while it is executing.

# g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.5.0-3ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)

**Comment by wannesm** [comment]
The c code now includes stdint.h to make it compatible with linux (tested on Ubuntu 18.04.5 LTS).
