### ISSUE TITLE
Hierarchical clustering for ndim

### ISSUE THREAD

**Issue by overdrivek** [wannesm/dtaidistance#93]
Is there way to perform heirarchical clustering with ndim data?
I tried the following: 

> model1 = clustering.Hierarchical(dtw_ndim.distance_matrix_fast,{})

it needed _ndim_ and _s_ as array list.. so i gave it,

> model1 = clustering.Hierarchical(dtw_ndim.distance_matrix_fast(s=array_list,ndim=3),{})

but then on fit i get the following error

> cluster_idx = model1.fit(array_list)
> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-130-b00b7121c79e> in <module>
>       1 model1 = clustering.Hierarchical(dtw_ndim.distance_matrix_fast(s=array_list,ndim=3),{})
> ----> 2 cluster_idx = model1.fit(data_iterator)
> 
> ~/miniconda3/envs/myenv/lib/python3.6/site-packages/dtaidistance/clustering/hierarchical.py in fit(self, series)
>      68         nb_series = len(series)
>      69         cluster_idx = dict()
> ---> 70         dists = self.dists_fun(series, **self.dists_options)
>      71         min_value = np.min(dists)
>      72         min_idxs = np.argwhere(dists == min_value)
> 
> TypeError: 'numpy.ndarray' object is not callable
> 

it would be great if there is a solution.

**Comment by wannesm** [comment]
You need to pass in the method, not the result of the distance_matrix method:

```
s = np.array([
    [[0.,0.], [0,0], [1,0], [2,0], [1,0], [0,0], [1,0], [0,0], [0,0]],
    [[0.,0.], [1,0], [2,0], [0,0], [0,0], [0,0], [0,0], [0,0], [0,0]],
    [[1.,0.], [2,0], [0,0], [0,0], [0,0], [0,0], [0,0], [1,0], [1,0]]])
model = clustering.Hierarchical(dtw_ndim.distance_matrix_fast, {'ndim':2})
cluster_idx = model.fit(s)
```

The visualization, however, does not work since it expects 1-dim series to plot.

**Comment by overdrivek** [comment]
great! it works.. thanks a lot.
