### ISSUE TITLE
Support for multiple versions of n-dimensional DTW?

### ISSUE THREAD

**Issue by JeongJuhyeon** [wannesm/dtaidistance#94]
[This paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5668684/) claims that the preferred method for n-dimensional DTW can differ depending on several factors. Does dtadistance.dtw_ndim create separate mappings for each dimension or one mapping that is applied to each dimension?

**Comment by wannesm** [comment]
The implementation is dependent n-dim DTW. For independent n-dim DTW you don't need a separate method since you can add the results of 1-dim DTW. I have clarified this in the docs in the latest commit 790413bd12c1c1632a1aff0d2fc897d48630e65d
