### ISSUE TITLE
Add tags 2.1.0, 2.1.1, 2.1.2 to repository

### ISSUE THREAD

**Issue by tomzx** [wannesm/dtaidistance#95]
Hello!

Would it be possible to have the git commit used to release 2.1.0, 2.1.1, 2.1.2 to pypi tagged and pushed to the repository? It would help identifying the differences between versions.

Thanks!

**Comment by wannesm** [comment]
Thanks for the suggestion. The tags are now pushed as part of the deploy script.

**Comment by tomzx** [comment]
Thanks @wannesm!
