### ISSUE TITLE
How to prevent infinity values?

### ISSUE THREAD

**Issue by StefanBloemheuvel** [wannesm/dtaidistance#96]
Hi package owners,

I want to calculate the dynamic time warp distance between all the variables (37) in my dataset with 2900+/- rows. However, almost all the values in the resulting dataframe of ds = dtw.distance_matrix_fast(np.matrix(my_dataset.values)). How can i prevent that? 

My dataset is structured like this:

```

      | sensor 1   | sensor 2     | sensor3
time1 | 0.60       | 0.55         | 0.68
time2 | 0.55       | 0.77         | 0.70
time3 | 0.58       | 0.70         | 0.69

```

I also tried transposing the dataframe but that did not help either. Should i decrease the number of rows in the time series? Or should the inf values be mapped to e.g., 0?

Kind regards and thanks in advance for creating this package,

Stefan

**Comment by wannesm** [comment]
This looks quite standard, so no reason for it to output inf, no(https://dtaidistance.readthedocs.io/en/latest/usage/dtw.html#dtw-between-multiple-time-series). You indeed need to transpose the matrix and drop the time index. Can you share more information about `my_dataset.values` (e.g. size, dtype, contains nan or inf)? I assume you have no other custom settings?

**Comment by StefanBloemheuvel** [comment]
hi wannesem, the size is (37, 2956), dtypes are floats and the data contains no nan's or infs. Also i used no custom settings. I removed the time index by using my_dataset.values, since it is originally a pandas dataframe. It also does not work when i only use the first 3 sensors in my dataframe, so comparing 3 time series. The output then  is:

```
array([[            inf, 6.95208187e-310],
       [            inf,             inf]])
```

**Comment by wannesm** [comment]
This is the output for comparing only two time series since the matrix is of size 2x2 (the 3 inf are there because it's an upper triangular matrix). The distance is practically zero so it seems that it's comparing identical series. Could you share the 3 time series (e.g. as a csv using `my_dataset_subsect.to_csv()`)?

**Comment by StefanBloemheuvel** [comment]
I have added a sample file to my github page, it is in the datafolder, which contains the first 4 sensors in my dataset. The link is: https://github.com/StefanBloemheuvel/GSP_Bridge

**Comment by wannesm** [comment]
For this sample, everything looks as expected when I run it. Maybe it's a conversion problem?

```
$ df = pd.read_csv('sample.csv', header=None)
$ print(df)
   0      1      2      ...  \
0 -0.064  0.076  0.066  ...   
1  0.807  0.752  0.779  ...   
2 -0.037  0.029  0.103  ...
3 -0.009  0.166  0.354  ...
$ dtaidistance.dtw.distance_matrix_fast(df.values)
array([[        inf, 44.77542412,  7.90449651,  9.5080814 ],
       [        inf,         inf, 48.10354657, 44.74612378],
       [        inf,         inf,         inf,  8.74034639],
       [        inf,         inf,         inf,         inf]])
```

**Comment by StefanBloemheuvel** [comment]
very weird, when i try to download the same file i get the same values as i got earlier. Should i have specific version of certain packages in order for it to work properly?

**Comment by StefanBloemheuvel** [comment]
Hi,

I tried running one of the examples for your website, and i get the following:

```
timeseries = np.array([
     [0., 0, 1, 2, 1, 0, 1, 0, 0],
     [0., 1, 2, 0, 0, 0, 0, 0, 0],
     [1., 2, 0, 0, 0, 0, 0, 1, 1],
     [0., 0, 1, 2, 1, 0, 1, 0, 0],
     [0., 1, 2, 0, 0, 0, 0, 0, 0],
     [1., 2, 0, 0, 0, 0, 0, 1, 1]])
ds = dtw.distance_matrix_fast(timeseries, block=((1, 4), (3, 5)))
print(ds)

array('d', [6.9321568068798e-310, 0.0, 1.0609978956e-313, 2.1219957915e-314, 6.9321568068798e-310])
```

Which is different from the expected result:

```
[1.4142  0.0000  2.2360  1.7320  1.4142]
```

Do you perhaps know what is going wrong here? I tried the example from https://dtaidistance.readthedocs.io/en/latest/usage/dtw.html#dtw-between-multiple-time-series

**Comment by wannesm** [comment]
Thanks for following up. This is an odd bug that I cannot reproduce. When copy-pasting your example, I  get the expected result, both for the pure Python version and C-based version:

```
>>> dtw.distance_matrix(timeseries, block=((1, 4), (3, 5)), compact=True, use_c=True)
array('d', [1.4142135623730951, 0.0, 2.23606797749979, 1.7320508075688772, 1.4142135623730951])
>>> dtw.distance_matrix(timeseries, block=((1, 4), (3, 5)), compact=True, use_c=False)
array('d', [1.4142135623730951, 0.0, 2.23606797749979, 1.7320508075688772, 1.4142135623730951])
```

Can you print some properties about the array and package? I included the outputs I see:

```
>>> print(timeseries.dtype)
float64
>>> print(timeseries.nbytes)
432
>>> print(timeseries.shape)
(6, 9)
>>> import dtaidistance
>>> print(dtaidistance.__version__)
2.1.2
>>> dtw.try_import_c()
```

**Comment by StefanBloemheuvel** [comment]
Thanks for your fast reply, the output for your questions are:

```
print(numerical.dtype)
float64
print(numerical.nbytes)
874976
print(numerical.shape)
(37,2956)
import dtaidistance
print(dtaidistance.__version__)
2.1.2
dtw.try_import_c()
print(np.__version__)
1.19.4
```

I will try updating my numpy version, that might have caused the issue

**Comment by wannesm** [comment]
These outputs show that you are not running the example from the documentation. The array is called `numerical` instead of `timeseries` and the numbers are a lot larger.

**Comment by StefanBloemheuvel** [comment]
Sorry i see indeed, the true numbers are:

```
print(numerical.dtype)
float64
print(numerical.nbytes)
432
print(numerical.shape)
(6,9)
import dtaidistance
print(dtaidistance.__version__)
2.1.2
dtw.try_import_c()
print(np.__version__)
1.19.5
```

**Comment by wannesm** [comment]
Just to be sure, is the output you generated by applying the method to the `numerical` array or the `timeseries` array?

**Comment by StefanBloemheuvel** [comment]
> Sorry i see indeed, the true numbers are:
> 
> ```
> print(timeseries.dtype)
> float64
> print(timeseries.nbytes)
> 432
> print(timeseries.shape)
> (6,9)
> import dtaidistance
> print(dtaidistance.__version__)
> 2.1.2
> dtw.try_import_c()
> print(np.__version__)
> 1.19.5
> ```

This is the output of the timeseries, so from the example from the website.

**Comment by wannesm** [comment]
Including the output
```
array('d', [6.9321568068798e-310, 0.0, 1.0609978956e-313, 2.1219957915e-314, 6.9321568068798e-310])
``` ?

**Comment by StefanBloemheuvel** [comment]
Yes, that is the output when running:

```
from dtaidistance import dtw
import numpy as np
timeseries = np.array([
     [0., 0, 1, 2, 1, 0, 1, 0, 0],
     [0., 1, 2, 0, 0, 0, 0, 0, 0],
     [1., 2, 0, 0, 0, 0, 0, 1, 1],
     [0., 0, 1, 2, 1, 0, 1, 0, 0],
     [0., 1, 2, 0, 0, 0, 0, 0, 0],
     [1., 2, 0, 0, 0, 0, 0, 1, 1]])
ds = dtw.distance_matrix_fast(timeseries, block=((1, 4), (3, 5)), compact=True)
print(ds)
>>> array('d', [6.9386596252499e-310, 0.0, 4.66839074027e-313, 5e-324, 6.9386596252499e-310])

**Comment by wannesm** [comment]
Can you also share the outputs when running?

```
dtw.distance_matrix_fast(timeseries)
dtw.distance_matrix(timeseries)
```

**Comment by StefanBloemheuvel** [comment]
```
dtw.distance_matrix_fast(timeseries)

>>> 
dtw.distance_matrix_fast(timeseries)
array([[0.00000000e+000, 0.00000000e+000, 6.93066068e-310,
                    nan, 0.00000000e+000, 2.24611795e-314],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        9.52182913e-090, 0.00000000e+000, 0.00000000e+000],
       [6.93066068e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [            nan, 9.52182913e-090, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [2.24611795e-314, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

dtw.distance_matrix(timeseries)
[[0.         1.41421356 2.23606798 0.         1.41421356 2.23606798]
 [1.41421356 0.         1.73205081 1.41421356 0.         1.73205081]
 [2.23606798 1.73205081 0.         2.23606798 1.73205081 0.        ]
 [0.         1.41421356 2.23606798 0.         1.41421356 2.23606798]
 [1.41421356 0.         1.73205081 1.41421356 0.         1.73205081]
 [2.23606798 1.73205081 0.         2.23606798 1.73205081 0.        ]]
```

Here there seems to be some more appropriate output.

**Comment by bramDelft** [comment]
Hi Stefan and Wannes,

I've got the same problem, dtw.distance_matrix_fast gives me the same results as Stefan. The dtw.distance_matrix given the right results but takes way longer..

Best,
Bram

**Comment by wannesm** [comment]
Thanks for the additional feedback. Can you also share the python version, the platform and compiler you are using? I have not yet been able to reproduce the bug on Linux (gcc), Macos (clang) or Windows (vsc).

**Comment by bramDelft** [comment]
Hi, I am using Python version 3.8.5 via Anaconda and the compiler I am using is windows (mvsc).

**Comment by wannesm** [comment]
I think I have identified the cause of this bug. Anaconda has (by default) no support to compile with OpenMP (thus for parallelization). The compilation prints (with `-vv` option):

```
clang: error: unsupported option '-fopenmp'
 WARNING: OpenMP is not available, disabling OpenMP (no parallel computing in C)
```

The `_fast` version has parallel set to True by default. I installed Anaconda and can replicate this behavior. It should print a warning (I can see one) but it does not throw an error. The matrix is thus a random initialization.

The simple solution is to use:

```
dtw.distance_matrix_fast(timeseries, parallel=False)
```

I will change the code to throw an error instead of just printing an error. And if time permits figure out how to enable OpenMP+Cython in Anaconda.

**Comment by wannesm** [comment]
The current version (2.2.2) on pipy will now raise an Exception if OpenMP is not available.
Avoiding OpenMP can be achieved with following settings:

```
dtw.distance_matrix(timeseries, use_c=False)  # Pure Python
dtw.distance_matrix(timeseries, use_c=True, parallel=False)  # Avoid parallel execution
dtw.distance_matrix(timeseries, use_c=True, parallel=True, use_mp=True)  # Use Python multiprocessing package for parallel execution
```

If someone has experience with installing openmp for anaconda or writing a conda package, contributions are welcome.

**Comment by wannesm** [comment]
The setup file is updated and the compilation with openmp now succeeds on anaconda+macos (could be you have to install openmp).
