### ISSUE TITLE
How to use trained clustering model for prediction?

### ISSUE THREAD

**Issue by ivaninHK** [wannesm/dtaidistance#97]
Nice library for calculating dynamic time warping, And it is really easy to use dtw for clustering. But I cannot find the way to use the fitted model for predicting the group of new data series.

from dtaidistance import dtw, clustering
s = np.array([
         [0., 0, 1, 2, 1, 0, 1, 0, 0],
         [0., 1, 2, 0, 0, 0, 0, 0, 0],
         [1., 2, 0, 0, 0, 0, 0, 1, 1],
         [0., 0, 1, 2, 1, 0, 1, 0, 0],
         [0., 1, 2, 0, 0, 0, 0, 0, 0],
         [1., 2, 0, 0, 0, 0, 0, 1, 1],
         [1., 2, 0, 0, 0, 0, 0, 1, 1]])

model = clustering.KMedoids(dtw.distance_matrix_fast, {}, k=3)
cluster_idx = model.fit(s)

Am I missing something? Thank you very much.

**Comment by wannesm** [comment]
The cluster_idx datastructure has as keys the medoids. You can perform DTW between the medoids and the new series. The medoid with the smallest dtw distance would be the predicted cluster.

Thus something like:

```
for medoid in cluster_idx.keys():
    dist = dtw.distance(s[medoid], new_unseen_series)
    print(f'DTW for medoid {medoid}: {dist}')
```
